name: blockhub_flutter
repository: https://github.com/mashevictor/blockhub

packages:
  - runtime-app
  - packages/blockhub_flutter_core
  - packages/capability_*

command:
  bootstrap:
    runPubGetInParallel: true
