/** Auto-generated by scripts/codegen-capability-manifest.py — do not edit */
export interface CapabilityManifestEntry {
  key: string
  name: string
  category: string
  widget: string
  agent_id: string
  web_pkg: string
  flutter_pkg: string
  route: string
  keywords: string[]
}
export const CAPABILITY_MANIFEST: CapabilityManifestEntry[] = [
  {
    "key": "announce_board",
    "name": "公告栏",
    "category": "通知集成",
    "widget": "InboxWidget",
    "agent_id": "notify",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_announce_board",
    "route": "/notifications",
    "keywords": []
  },
  {
    "key": "approval_conditional",
    "name": "条件分支审批",
    "category": "流程审批",
    "widget": "FormWidget",
    "agent_id": "approval",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_approval_conditional",
    "route": "/approval",
    "keywords": []
  },
  {
    "key": "approval_countersign",
    "name": "会签/或签",
    "category": "流程审批",
    "widget": "FormWidget",
    "agent_id": "approval",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_approval_countersign",
    "route": "/approval",
    "keywords": []
  },
  {
    "key": "approval_esign",
    "name": "电子签批",
    "category": "流程审批",
    "widget": "FormWidget",
    "agent_id": "approval",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_approval_esign",
    "route": "/approval",
    "keywords": []
  },
  {
    "key": "approval_flow",
    "name": "审批流",
    "category": "流程审批",
    "widget": "FormWidget",
    "agent_id": "approval",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_approval_flow",
    "route": "/approval",
    "keywords": [
      "审批",
      "请假",
      "报销",
      "流程",
      "待办",
      "会签",
      "合同",
      "盖章",
      "签章",
      "电子签"
    ]
  },
  {
    "key": "approval_inbox",
    "name": "待办中心",
    "category": "流程审批",
    "widget": "ListWidget",
    "agent_id": "approval",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_approval_inbox",
    "route": "/inbox",
    "keywords": [
      "待办",
      "已办",
      "inbox",
      "案件",
      "进度跟踪",
      "跟踪"
    ]
  },
  {
    "key": "approval_remind",
    "name": "超时催办",
    "category": "流程审批",
    "widget": "ListWidget",
    "agent_id": "approval",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_approval_remind",
    "route": "/inbox",
    "keywords": []
  },
  {
    "key": "asset_manage",
    "name": "资产管理",
    "category": "IT与资产",
    "widget": "AssetManageWidget",
    "agent_id": "asset_manage",
    "web_pkg": "@blockhub/web-capability-asset-manage",
    "flutter_pkg": "capability_asset_manage",
    "route": "/asset-manage",
    "keywords": [
      "资产",
      "领用",
      "固定资产",
      "资产盘点",
      "资产报废"
    ]
  },
  {
    "key": "audit_log",
    "name": "操作审计日志",
    "category": "权限安全",
    "widget": "AuditWidget",
    "agent_id": "creation",
    "web_pkg": "@blockhub/web-capability-audit-log",
    "flutter_pkg": "capability_audit_log",
    "route": "/audit-log",
    "keywords": []
  },
  {
    "key": "auth_sso",
    "name": "SSO 单点登录",
    "category": "权限安全",
    "widget": "SSOWidget",
    "agent_id": "integration",
    "web_pkg": "@blockhub/web-capability-auth-sso",
    "flutter_pkg": "capability_auth_sso",
    "route": "/auth-sso",
    "keywords": []
  },
  {
    "key": "campaign_ops",
    "name": "活动运营",
    "category": "营销运营",
    "widget": "CampaignOpsWidget",
    "agent_id": "campaign_ops",
    "web_pkg": "@blockhub/web-capability-campaign-ops",
    "flutter_pkg": "capability_campaign_ops",
    "route": "/campaign-ops",
    "keywords": [
      "活动运营",
      "活动策划",
      "报名统计",
      "转化复盘",
      "活动管理"
    ]
  },
  {
    "key": "chart_basic",
    "name": "折线/柱状图",
    "category": "可视化",
    "widget": "DashboardWidget",
    "agent_id": "report",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_chart_basic",
    "route": "/dashboard",
    "keywords": []
  },
  {
    "key": "chart_dashboard",
    "name": "数据看板",
    "category": "可视化",
    "widget": "DashboardWidget",
    "agent_id": "report",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_chart_dashboard",
    "route": "/dashboard",
    "keywords": [
      "看板",
      "dashboard",
      "报表",
      "统计",
      "数据大屏"
    ]
  },
  {
    "key": "chart_funnel",
    "name": "销售漏斗",
    "category": "可视化",
    "widget": "FunnelWidget",
    "agent_id": "report",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_chart_funnel",
    "route": "/dashboard",
    "keywords": [
      "漏斗",
      "转化",
      "商机阶段"
    ]
  },
  {
    "key": "chart_kpi_card",
    "name": "KPI 卡片",
    "category": "可视化",
    "widget": "DashboardWidget",
    "agent_id": "report",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_chart_kpi_card",
    "route": "/dashboard",
    "keywords": []
  },
  {
    "key": "chat_qa",
    "name": "智能问答",
    "category": "智能交互",
    "widget": "ChatWidget",
    "agent_id": "chat_qa",
    "web_pkg": "@blockhub/web-capability-chat",
    "flutter_pkg": "capability_chat_qa",
    "route": "/chat",
    "keywords": [
      "问答",
      "faq",
      "客服",
      "智能问",
      "对话"
    ]
  },
  {
    "key": "chat_summary",
    "name": "对话摘要",
    "category": "智能交互",
    "widget": "SummaryWidget",
    "agent_id": "chat_qa",
    "web_pkg": "@blockhub/web-capability-chat",
    "flutter_pkg": "capability_chat_summary",
    "route": "/summary",
    "keywords": [
      "摘要",
      "总结",
      "会议纪要"
    ]
  },
  {
    "key": "chat_voice",
    "name": "语音问答",
    "category": "智能交互",
    "widget": "VoiceWidget",
    "agent_id": "chat_qa",
    "web_pkg": "@blockhub/web-capability-chat",
    "flutter_pkg": "capability_chat_voice",
    "route": "/chat",
    "keywords": [
      "语音问答",
      "语音助手"
    ]
  },
  {
    "key": "class_schedule",
    "name": "课表查询",
    "category": "教育培训",
    "widget": "ClassScheduleWidget",
    "agent_id": "class_schedule",
    "web_pkg": "@blockhub/web-capability-class-schedule",
    "flutter_pkg": "capability_class_schedule",
    "route": "/class-schedule",
    "keywords": [
      "课表查询",
      "课程表",
      "考试安排",
      "教室查询",
      "课表"
    ]
  },
  {
    "key": "cold_chain_alert",
    "name": "冷链告警",
    "category": "物流仓储",
    "widget": "ColdChainAlertWidget",
    "agent_id": "cold_chain_alert",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/cold-chain-alert",
    "keywords": [
      "冷链",
      "温控",
      "温湿度",
      "冷藏"
    ]
  },
  {
    "key": "contract_editor",
    "name": "合同编辑器",
    "category": "合同签章",
    "widget": "LegalCaseWidget",
    "agent_id": "contract_esign",
    "web_pkg": "@blockhub/web-capability-legal-case",
    "flutter_pkg": "capability_contract_editor",
    "route": "/legal-case",
    "keywords": []
  },
  {
    "key": "contract_pdf",
    "name": "合同 PDF",
    "category": "合同签章",
    "widget": "LegalCaseWidget",
    "agent_id": "contract_esign",
    "web_pkg": "@blockhub/web-capability-legal-case",
    "flutter_pkg": "capability_contract_pdf",
    "route": "/legal-case",
    "keywords": []
  },
  {
    "key": "contract_seal",
    "name": "电子公章",
    "category": "合同签章",
    "widget": "LegalCaseWidget",
    "agent_id": "contract_esign",
    "web_pkg": "@blockhub/web-capability-legal-case",
    "flutter_pkg": "capability_contract_seal",
    "route": "/legal-case",
    "keywords": []
  },
  {
    "key": "contract_sign",
    "name": "手写签名",
    "category": "合同签章",
    "widget": "LegalCaseWidget",
    "agent_id": "contract_esign",
    "web_pkg": "@blockhub/web-capability-legal-case",
    "flutter_pkg": "capability_contract_sign",
    "route": "/legal-case",
    "keywords": []
  },
  {
    "key": "creation",
    "name": "智能创建",
    "category": "平台能力",
    "widget": "CreationWizard",
    "agent_id": "creation",
    "web_pkg": "@blockhub/web-capability-creation",
    "flutter_pkg": "capability_creation",
    "route": "/creation",
    "keywords": []
  },
  {
    "key": "credit_approval",
    "name": "授信审批",
    "category": "金融服务",
    "widget": "CreditApprovalWidget",
    "agent_id": "credit_approval",
    "web_pkg": "@blockhub/web-capability-finance",
    "flutter_pkg": "capability_finance",
    "route": "/credit-approval",
    "keywords": [
      "授信",
      "额度审批",
      "贷后",
      "信贷审批",
      "担保"
    ]
  },
  {
    "key": "data_export",
    "name": "数据导出",
    "category": "知识数据",
    "widget": "DashboardWidget",
    "agent_id": "report",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_data_export",
    "route": "/dashboard",
    "keywords": []
  },
  {
    "key": "data_nl_query",
    "name": "智能问数",
    "category": "知识数据",
    "widget": "NLQueryWidget",
    "agent_id": "report",
    "web_pkg": "@blockhub/web-capability-data-nl-query",
    "flutter_pkg": "capability_data_nl_query",
    "route": "/nl-query",
    "keywords": [
      "问数",
      "自然语言查数",
      "sql查询",
      "查销售",
      "查数据",
      "业绩数据"
    ]
  },
  {
    "key": "deal_evidence",
    "name": "成交证据",
    "category": "销售行业",
    "widget": "DealEvidenceWidget",
    "agent_id": "deal_evidence",
    "web_pkg": "@blockhub/web-capability-deal-evidence",
    "flutter_pkg": "capability_deal_evidence",
    "route": "/deal-evidence",
    "keywords": [
      "成交证据",
      "证据门禁",
      "买方回执",
      "POC结果",
      "阶段晋级"
    ]
  },
  {
    "key": "deco_material",
    "name": "装修选材",
    "category": "建筑工程",
    "widget": "DecoMaterialWidget",
    "agent_id": "deco_material",
    "web_pkg": "@blockhub/web-capability-deco-material",
    "flutter_pkg": "capability_deco_material",
    "route": "/deco-material",
    "keywords": [
      "装修选材",
      "材料选型",
      "进度验收",
      "家装预算",
      "装修"
    ]
  },
  {
    "key": "delivery_order",
    "name": "外卖配送",
    "category": "物流仓储",
    "widget": "DeliveryOrderWidget",
    "agent_id": "delivery_order",
    "web_pkg": "@blockhub/web-capability-delivery-order",
    "flutter_pkg": "capability_delivery_order",
    "route": "/delivery-order",
    "keywords": [
      "外卖配送",
      "外卖",
      "骑手调度",
      "配送异常",
      "订单跟踪",
      "运单跟踪"
    ]
  },
  {
    "key": "device_repair",
    "name": "设备报修",
    "category": "现场运维",
    "widget": "DeviceRepairWidget",
    "agent_id": "device_repair",
    "web_pkg": "@blockhub/web-capability-device-repair",
    "flutter_pkg": "capability_device_repair",
    "route": "/device-repair",
    "keywords": [
      "设备报修",
      "报修",
      "扫码提单",
      "维修工单",
      "产线故障",
      "设备故障"
    ]
  },
  {
    "key": "dock_queue",
    "name": "装卸排队",
    "category": "物流仓储",
    "widget": "DockQueueWidget",
    "agent_id": "dock_queue",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/dock-queue",
    "keywords": [
      "月台",
      "装卸",
      "排队叫号",
      "场站"
    ]
  },
  {
    "key": "due_diligence",
    "name": "尽调报告",
    "category": "金融服务",
    "widget": "DueDiligenceWidget",
    "agent_id": "due_diligence",
    "web_pkg": "@blockhub/web-capability-finance",
    "flutter_pkg": "capability_finance",
    "route": "/due-diligence",
    "keywords": [
      "尽调",
      "投研尽调",
      "投后管理",
      "尽职调查"
    ]
  },
  {
    "key": "energy_carbon",
    "name": "能耗碳排",
    "category": "绿色制造",
    "widget": "EnergyCarbonWidget",
    "agent_id": "energy_carbon",
    "web_pkg": "@blockhub/web-capability-mfg-ops",
    "flutter_pkg": "capability_energy_carbon",
    "route": "/energy-carbon",
    "keywords": [
      "能耗",
      "碳排",
      "用电",
      "绿色制造"
    ]
  },
  {
    "key": "erp_connector",
    "name": "ERP对接",
    "category": "外部集成",
    "widget": "ERPWidget",
    "agent_id": "integration",
    "web_pkg": "@blockhub/web-capability-integration",
    "flutter_pkg": "capability_erp_connector",
    "route": "/erp",
    "keywords": [
      "erp",
      "sap",
      "用友",
      "金蝶"
    ]
  },
  {
    "key": "expense_claim",
    "name": "报销记账",
    "category": "财务法务",
    "widget": "ExpenseClaimWidget",
    "agent_id": "expense_claim",
    "web_pkg": "@blockhub/web-capability-expense-claim",
    "flutter_pkg": "capability_expense_claim",
    "route": "/expense-claim",
    "keywords": [
      "报销记账",
      "费用报销",
      "发票上传",
      "报销申请"
    ]
  },
  {
    "key": "finance_aml",
    "name": "反洗钱监测",
    "category": "金融服务",
    "widget": "FinanceAmlWidget",
    "agent_id": "finance_aml",
    "web_pkg": "@blockhub/web-capability-finance",
    "flutter_pkg": "capability_finance",
    "route": "/finance-aml",
    "keywords": [
      "反洗钱",
      "AML",
      "可疑交易",
      "风控预警",
      "欺诈预警"
    ]
  },
  {
    "key": "finance_kyc",
    "name": "金融KYC",
    "category": "金融服务",
    "widget": "FinanceKycWidget",
    "agent_id": "finance_kyc",
    "web_pkg": "@blockhub/web-capability-finance",
    "flutter_pkg": "capability_finance",
    "route": "/finance-kyc",
    "keywords": [
      "KYC",
      "开户核验",
      "适当性",
      "身份核验",
      "客户尽调开户"
    ]
  },
  {
    "key": "finance_news",
    "name": "行业新闻Agent",
    "category": "金融服务",
    "widget": "FinanceNewsWidget",
    "agent_id": "finance_news",
    "web_pkg": "@blockhub/web-capability-finance",
    "flutter_pkg": "capability_finance",
    "route": "/finance-news",
    "keywords": [
      "行业新闻",
      "新闻Agent",
      "金融新闻",
      "必读摘要",
      "热议",
      "一页纸"
    ]
  },
  {
    "key": "fitness_checkin",
    "name": "健身打卡",
    "category": "生活服务",
    "widget": "FitnessCheckinWidget",
    "agent_id": "fitness_checkin",
    "web_pkg": "@blockhub/web-capability-fitness-checkin",
    "flutter_pkg": "capability_fitness_checkin",
    "route": "/fitness-checkin",
    "keywords": [
      "健身打卡",
      "课程预约",
      "训练打卡",
      "教练答疑",
      "健身"
    ]
  },
  {
    "key": "fleet_dispatch",
    "name": "车辆调度",
    "category": "物流仓储",
    "widget": "FleetDispatchWidget",
    "agent_id": "fleet_dispatch",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/fleet-dispatch",
    "keywords": [
      "车辆调度",
      "派车",
      "司机",
      "车队"
    ]
  },
  {
    "key": "flutter_biometric",
    "name": "生物识别",
    "category": "Flutter工具",
    "widget": "BioWidget",
    "agent_id": "security",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_biometric",
    "route": "/flutter-biometric",
    "keywords": [
      "指纹",
      "面容",
      "face id",
      "生物识别",
      "解锁"
    ]
  },
  {
    "key": "flutter_camera",
    "name": "拍照上传",
    "category": "Flutter工具",
    "widget": "CameraWidget",
    "agent_id": "integration",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_camera",
    "route": "/flutter-camera",
    "keywords": [
      "拍照",
      "相机",
      "上传照片",
      "现场拍照",
      "ocr识别",
      "巡检",
      "隐患"
    ]
  },
  {
    "key": "flutter_chart",
    "name": "移动图表",
    "category": "Flutter工具",
    "widget": "MobileChartWidget",
    "agent_id": "report",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_chart",
    "route": "/flutter-chart",
    "keywords": [
      "图表",
      "折线图",
      "柱状图",
      "移动端看板"
    ]
  },
  {
    "key": "flutter_file_picker",
    "name": "文件选择",
    "category": "Flutter工具",
    "widget": "FileWidget",
    "agent_id": "kb",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_file_picker",
    "route": "/flutter-file-picker",
    "keywords": [
      "选文件",
      "附件",
      "上传文件",
      "导入excel",
      "pdf上传"
    ]
  },
  {
    "key": "flutter_geolocation",
    "name": "定位签到",
    "category": "Flutter工具",
    "widget": "GeoWidget",
    "agent_id": "integration",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_geolocation",
    "route": "/flutter-geolocation",
    "keywords": [
      "定位",
      "gps",
      "签到",
      "外勤",
      "打卡定位",
      "轨迹",
      "工地"
    ]
  },
  {
    "key": "flutter_map",
    "name": "地图导航",
    "category": "Flutter工具",
    "widget": "MapWidget",
    "agent_id": "integration",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_map",
    "route": "/flutter-map",
    "keywords": [
      "地图",
      "导航",
      "路线",
      "门店分布",
      "派单地图",
      "调度"
    ]
  },
  {
    "key": "flutter_offline",
    "name": "离线缓存",
    "category": "Flutter工具",
    "widget": "OfflineWidget",
    "agent_id": "integration",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_offline",
    "route": "/flutter-offline",
    "keywords": [
      "离线",
      "缓存",
      "无网络",
      "本地存储",
      "断网"
    ]
  },
  {
    "key": "flutter_pdf",
    "name": "PDF预览",
    "category": "Flutter工具",
    "widget": "PdfWidget",
    "agent_id": "kb",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_pdf",
    "route": "/flutter-pdf",
    "keywords": [
      "pdf",
      "预览文档",
      "合同预览"
    ]
  },
  {
    "key": "flutter_push",
    "name": "移动推送",
    "category": "Flutter工具",
    "widget": "PushWidget",
    "agent_id": "notify",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_push",
    "route": "/flutter-push",
    "keywords": [
      "推送",
      "push",
      "消息推送",
      "离线推送"
    ]
  },
  {
    "key": "flutter_scan_qr",
    "name": "扫码识别",
    "category": "Flutter工具",
    "widget": "ScanWidget",
    "agent_id": "integration",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_scan_qr",
    "route": "/flutter-scan-qr",
    "keywords": [
      "扫码",
      "二维码",
      "条形码",
      "qr",
      "盘点扫码"
    ]
  },
  {
    "key": "flutter_signature",
    "name": "手写签名",
    "category": "Flutter工具",
    "widget": "SignWidget",
    "agent_id": "approval",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_signature",
    "route": "/flutter-signature",
    "keywords": [
      "签名",
      "手写",
      "电子签",
      "签批"
    ]
  },
  {
    "key": "flutter_speech",
    "name": "语音交互",
    "category": "Flutter工具",
    "widget": "SpeechWidget",
    "agent_id": "chat_qa",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_speech",
    "route": "/flutter-speech",
    "keywords": [
      "语音",
      "说话",
      "tts",
      "语音输入",
      "朗读"
    ]
  },
  {
    "key": "flutter_webview",
    "name": "内嵌网页",
    "category": "Flutter工具",
    "widget": "WebViewWidget",
    "agent_id": "integration",
    "web_pkg": "",
    "flutter_pkg": "capability_flutter_webview",
    "route": "/flutter-webview",
    "keywords": [
      "webview",
      "内嵌网页",
      "h5",
      "h5页面",
      "嵌入系统",
      "旧系统"
    ]
  },
  {
    "key": "form_widget",
    "name": "表单组件",
    "category": "平台能力",
    "widget": "FormWidget",
    "agent_id": "creation",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_form_widget",
    "route": "/form",
    "keywords": [
      "表单",
      "问卷",
      "席位",
      "登记",
      "填写"
    ]
  },
  {
    "key": "freight_settle",
    "name": "运费结算",
    "category": "物流仓储",
    "widget": "FreightSettleWidget",
    "agent_id": "freight_settle",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/freight-settle",
    "keywords": [
      "运费",
      "承运商结算",
      "运费对账"
    ]
  },
  {
    "key": "game_2048",
    "name": "2048",
    "category": "游戏娱乐",
    "widget": "Game2048Widget",
    "agent_id": "game_support",
    "web_pkg": "@blockhub/web-capability-game-2048",
    "flutter_pkg": "capability_game_2048",
    "route": "/game-2048",
    "keywords": [
      "2048",
      "数字合成",
      "合成2048",
      "益智2048",
      "玩2048",
      "2048小游戏",
      "数字方块"
    ]
  },
  {
    "key": "game_support",
    "name": "玩家FAQ",
    "category": "游戏娱乐",
    "widget": "GameSupportWidget",
    "agent_id": "game_support",
    "web_pkg": "@blockhub/web-capability-game-support",
    "flutter_pkg": "capability_game_support",
    "route": "/game-support",
    "keywords": [
      "玩家FAQ",
      "玩家攻略",
      "客服工单",
      "活动规则",
      "游戏FAQ",
      "玩家支持"
    ]
  },
  {
    "key": "gov_service",
    "name": "政务办事",
    "category": "政务公用",
    "widget": "GovServiceWidget",
    "agent_id": "gov_service",
    "web_pkg": "@blockhub/web-capability-gov-service",
    "flutter_pkg": "capability_gov_service",
    "route": "/gov-service",
    "keywords": [
      "政务办事",
      "办事指南",
      "诉求提交",
      "进度查询",
      "政务"
    ]
  },
  {
    "key": "hire_onboard",
    "name": "招聘入职",
    "category": "人事行政",
    "widget": "HireOnboardWidget",
    "agent_id": "hire_onboard",
    "web_pkg": "@blockhub/web-capability-hire-onboard",
    "flutter_pkg": "capability_hire_onboard",
    "route": "/hire-onboard",
    "keywords": [
      "招聘入职",
      "招聘管理",
      "简历筛选",
      "入职指引"
    ]
  },
  {
    "key": "homework_qa",
    "name": "作业答疑",
    "category": "教育培训",
    "widget": "HomeworkQaWidget",
    "agent_id": "homework_qa",
    "web_pkg": "@blockhub/web-capability-homework-qa",
    "flutter_pkg": "capability_homework_qa",
    "route": "/homework-qa",
    "keywords": [
      "作业答疑",
      "作业提交",
      "课程答疑",
      "错题",
      "错题巩固"
    ]
  },
  {
    "key": "hotel_booking",
    "name": "酒店预订",
    "category": "酒店餐饮",
    "widget": "HotelBookingWidget",
    "agent_id": "hotel_booking",
    "web_pkg": "@blockhub/web-capability-hotel-booking",
    "flutter_pkg": "capability_hotel_booking",
    "route": "/hotel-booking",
    "keywords": [
      "酒店预订",
      "客房预订",
      "入住",
      "退房",
      "订房"
    ]
  },
  {
    "key": "house_viewing",
    "name": "看房签约",
    "category": "房地产",
    "widget": "HouseViewingWidget",
    "agent_id": "house_viewing",
    "web_pkg": "@blockhub/web-capability-house-viewing",
    "flutter_pkg": "capability_house_viewing",
    "route": "/house-viewing",
    "keywords": [
      "看房签约",
      "看房预约",
      "意向登记",
      "签约跟进",
      "带看"
    ]
  },
  {
    "key": "insurance_case",
    "name": "保险核保理赔",
    "category": "金融服务",
    "widget": "InsuranceCaseWidget",
    "agent_id": "insurance_case",
    "web_pkg": "@blockhub/web-capability-finance",
    "flutter_pkg": "capability_finance",
    "route": "/insurance-case",
    "keywords": [
      "核保",
      "理赔",
      "保险报案",
      "承保"
    ]
  },
  {
    "key": "integration",
    "name": "外部数据对接",
    "category": "外部集成",
    "widget": "ERPWidget",
    "agent_id": "integration",
    "web_pkg": "@blockhub/web-capability-integration",
    "flutter_pkg": "capability_integration",
    "route": "/erp",
    "keywords": []
  },
  {
    "key": "inventory_count",
    "name": "库存盘点",
    "category": "仓储物流",
    "widget": "InventoryCountWidget",
    "agent_id": "inventory_count",
    "web_pkg": "@blockhub/web-capability-inventory-count",
    "flutter_pkg": "capability_inventory_count",
    "route": "/inventory-count",
    "keywords": [
      "库存",
      "盘点",
      "SKU",
      "货位",
      "补货",
      "仓储"
    ]
  },
  {
    "key": "it_helpdesk",
    "name": "IT报障",
    "category": "IT与资产",
    "widget": "ItTicketWidget",
    "agent_id": "it_ticket",
    "web_pkg": "@blockhub/web-capability-it-ticket",
    "flutter_pkg": "capability_it_helpdesk",
    "route": "/it-ticket",
    "keywords": [
      "报障",
      "it工单",
      "电脑故障",
      "helpdesk",
      "售后工单",
      "工单"
    ]
  },
  {
    "key": "it_ticket",
    "name": "IT报障",
    "category": "IT与资产",
    "widget": "ItTicketWidget",
    "agent_id": "it_ticket",
    "web_pkg": "@blockhub/web-capability-it-ticket",
    "flutter_pkg": "capability_it_ticket",
    "route": "/it-ticket",
    "keywords": [
      "IT报障",
      "报障",
      "电脑故障",
      "网络故障",
      "账号权限",
      "helpdesk"
    ]
  },
  {
    "key": "kb_document",
    "name": "知识库",
    "category": "知识数据",
    "widget": "KBUploadWidget",
    "agent_id": "kb",
    "web_pkg": "@blockhub/web-capability-kb",
    "flutter_pkg": "capability_kb_document",
    "route": "/kb",
    "keywords": [
      "知识库",
      "文档",
      "制度",
      "手册",
      "sop"
    ]
  },
  {
    "key": "kb_search",
    "name": "语义检索",
    "category": "知识数据",
    "widget": "KBUploadWidget",
    "agent_id": "kb",
    "web_pkg": "@blockhub/web-capability-kb",
    "flutter_pkg": "capability_kb_search",
    "route": "/kb",
    "keywords": []
  },
  {
    "key": "kill_pipeline",
    "name": "杀单工作台",
    "category": "销售行业",
    "widget": "KillPipelineWidget",
    "agent_id": "kill_pipeline",
    "web_pkg": "@blockhub/web-capability-kill-pipeline",
    "flutter_pkg": "capability_kill_pipeline",
    "route": "/kill-pipeline",
    "keywords": [
      "杀单",
      "丢单原因",
      "清理管线",
      "假管线",
      "赢率学习"
    ]
  },
  {
    "key": "leave_request",
    "name": "请假审批",
    "category": "人事行政",
    "widget": "LeaveRequestWidget",
    "agent_id": "leave_request",
    "web_pkg": "@blockhub/web-capability-leave-request",
    "flutter_pkg": "capability_leave_request",
    "route": "/leave-request",
    "keywords": [
      "请假审批",
      "请假申请",
      "假期余额",
      "请假"
    ]
  },
  {
    "key": "legal_case",
    "name": "法务合同",
    "category": "法律服务",
    "widget": "LegalCaseWidget",
    "agent_id": "legal_case",
    "web_pkg": "@blockhub/web-capability-legal-case",
    "flutter_pkg": "capability_legal_case",
    "route": "/legal-case",
    "keywords": [
      "法务合同",
      "合同审查",
      "法规检索",
      "案件跟踪",
      "法务"
    ]
  },
  {
    "key": "list_widget",
    "name": "列表组件",
    "category": "平台能力",
    "widget": "ListWidget",
    "agent_id": "creation",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_list_widget",
    "route": "/list",
    "keywords": [
      "列表",
      "清单",
      "目录",
      "席位安排"
    ]
  },
  {
    "key": "logistics_exception",
    "name": "物流异常",
    "category": "物流仓储",
    "widget": "LogisticsExceptionWidget",
    "agent_id": "logistics_exception",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/logistics-exception",
    "keywords": [
      "物流异常",
      "破损",
      "延误",
      "丢件",
      "危险品"
    ]
  },
  {
    "key": "maintenance_plan",
    "name": "保养计划",
    "category": "设备管理",
    "widget": "MaintenancePlanWidget",
    "agent_id": "maintenance_plan",
    "web_pkg": "@blockhub/web-capability-mfg-ops",
    "flutter_pkg": "capability_maintenance_plan",
    "route": "/maintenance-plan",
    "keywords": [
      "保养",
      "维保计划",
      "设备保养",
      "到期提醒"
    ]
  },
  {
    "key": "material_issue",
    "name": "物料领用",
    "category": "物料管理",
    "widget": "MaterialIssueWidget",
    "agent_id": "material_issue",
    "web_pkg": "@blockhub/web-capability-mfg-ops",
    "flutter_pkg": "capability_material_issue",
    "route": "/material-issue",
    "keywords": [
      "领料",
      "退料",
      "物料领用",
      "生产领料"
    ]
  },
  {
    "key": "med_triage",
    "name": "医疗导诊",
    "category": "患者服务",
    "widget": "MedTriageWidget",
    "agent_id": "med_triage",
    "web_pkg": "@blockhub/web-capability-med-triage",
    "flutter_pkg": "capability_med_triage",
    "route": "/med-triage",
    "keywords": [
      "医疗导诊",
      "智能导诊",
      "就医指南",
      "导诊",
      "科室",
      "预问诊",
      "症状"
    ]
  },
  {
    "key": "meeting_booking",
    "name": "会议室预约",
    "category": "人事行政",
    "widget": "MeetingBookingWidget",
    "agent_id": "meeting_booking",
    "web_pkg": "@blockhub/web-capability-meeting-booking",
    "flutter_pkg": "capability_meeting_booking",
    "route": "/meeting-booking",
    "keywords": [
      "会议室",
      "预约会议",
      "订会议室",
      "客房预订",
      "课程预约"
    ]
  },
  {
    "key": "member_loyalty",
    "name": "会员营销",
    "category": "营销运营",
    "widget": "MemberLoyaltyWidget",
    "agent_id": "member_loyalty",
    "web_pkg": "@blockhub/web-capability-member-loyalty",
    "flutter_pkg": "capability_member_loyalty",
    "route": "/member-loyalty",
    "keywords": [
      "会员营销",
      "会员积分",
      "会员管理",
      "促销",
      "券码",
      "积分兑换",
      "触达"
    ]
  },
  {
    "key": "mfg_oee",
    "name": "生产日报OEE",
    "category": "生产管理",
    "widget": "MfgOeeWidget",
    "agent_id": "mfg_oee",
    "web_pkg": "@blockhub/web-capability-mfg-ops",
    "flutter_pkg": "capability_mfg_oee",
    "route": "/mfg-oee",
    "keywords": [
      "OEE",
      "稼动率",
      "生产日报",
      "产量",
      "停机"
    ]
  },
  {
    "key": "multi_agent",
    "name": "多助手",
    "category": "智能交互",
    "widget": "MultiAgentWidget",
    "agent_id": "chat_qa",
    "web_pkg": "@blockhub/web-capability-multi-agent",
    "flutter_pkg": "capability_multi_agent",
    "route": "/multi-agent",
    "keywords": [
      "多助手",
      "multi agent"
    ]
  },
  {
    "key": "notify_email",
    "name": "邮件通知",
    "category": "通知集成",
    "widget": "EmailWidget",
    "agent_id": "notify",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_notify_email",
    "route": "/email",
    "keywords": [
      "邮件",
      "email",
      "发邮件"
    ]
  },
  {
    "key": "notify_im",
    "name": "企微钉钉飞书",
    "category": "通知集成",
    "widget": "IMWidget",
    "agent_id": "notify",
    "web_pkg": "@blockhub/web-capability-integration",
    "flutter_pkg": "capability_notify_im",
    "route": "/im",
    "keywords": [
      "企微",
      "钉钉",
      "企业微信",
      "飞书",
      "webhook",
      "群机器人"
    ]
  },
  {
    "key": "notify_inapp",
    "name": "站内信",
    "category": "通知集成",
    "widget": "InboxWidget",
    "agent_id": "notify",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_notify_inapp",
    "route": "/notifications",
    "keywords": [
      "站内",
      "消息中心",
      "提醒",
      "通知"
    ]
  },
  {
    "key": "nurse_shift",
    "name": "护士排班",
    "category": "患者服务",
    "widget": "NurseShiftWidget",
    "agent_id": "nurse_shift",
    "web_pkg": "@blockhub/web-capability-nurse-shift",
    "flutter_pkg": "capability_nurse_shift",
    "route": "/nurse-shift",
    "keywords": [
      "护士排班",
      "调班",
      "排班",
      "值班",
      "换班"
    ]
  },
  {
    "key": "oa_connector",
    "name": "OA 连接器",
    "category": "外部集成",
    "widget": "OAWidget",
    "agent_id": "integration",
    "web_pkg": "@blockhub/web-capability-oa-connector",
    "flutter_pkg": "capability_oa_connector",
    "route": "/oa-connector",
    "keywords": []
  },
  {
    "key": "ops_kpi",
    "name": "经营看板",
    "category": "数据报表",
    "widget": "OpsKpiWidget",
    "agent_id": "ops_kpi",
    "web_pkg": "@blockhub/web-capability-ops-kpi",
    "flutter_pkg": "capability_ops_kpi",
    "route": "/ops-kpi",
    "keywords": [
      "经营看板",
      "经营指标",
      "自然语言查数",
      "老板看板"
    ]
  },
  {
    "key": "pet_clinic",
    "name": "宠物问诊",
    "category": "医疗健康",
    "widget": "PetClinicWidget",
    "agent_id": "pet_clinic",
    "web_pkg": "@blockhub/web-capability-pet-clinic",
    "flutter_pkg": "capability_pet_clinic",
    "route": "/pet-clinic",
    "keywords": [
      "宠物问诊",
      "宠物健康",
      "预约就诊",
      "疫苗提醒",
      "宠物"
    ]
  },
  {
    "key": "pod_signoff",
    "name": "签收确认",
    "category": "物流仓储",
    "widget": "PodSignoffWidget",
    "agent_id": "pod_signoff",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/pod-signoff",
    "keywords": [
      "签收",
      "POD",
      "妥投",
      "拒收"
    ]
  },
  {
    "key": "policy_qa",
    "name": "制度问答",
    "category": "知识协同",
    "widget": "PolicyQaWidget",
    "agent_id": "policy_qa",
    "web_pkg": "@blockhub/web-capability-policy-qa",
    "flutter_pkg": "capability_policy_qa",
    "route": "/policy-qa",
    "keywords": [
      "制度问答",
      "制度政策",
      "福利政策",
      "制度查询"
    ]
  },
  {
    "key": "property_repair",
    "name": "物业报修",
    "category": "生活服务",
    "widget": "PropertyRepairWidget",
    "agent_id": "property_repair",
    "web_pkg": "@blockhub/web-capability-property-repair",
    "flutter_pkg": "capability_property_repair",
    "route": "/property-repair",
    "keywords": [
      "物业报修",
      "业主报修",
      "社区报修",
      "工单",
      "维修"
    ]
  },
  {
    "key": "quality_inspect",
    "name": "质检SOP",
    "category": "现场运维",
    "widget": "QualityInspectWidget",
    "agent_id": "quality_inspect",
    "web_pkg": "@blockhub/web-capability-quality-inspect",
    "flutter_pkg": "capability_quality_inspect",
    "route": "/quality-inspect",
    "keywords": [
      "质检",
      "SOP",
      "工艺",
      "不合格",
      "终检",
      "安环",
      "隐患"
    ]
  },
  {
    "key": "quote_contract",
    "name": "报价合同",
    "category": "销售行业",
    "widget": "QuoteContractWidget",
    "agent_id": "quote_contract",
    "web_pkg": "@blockhub/web-capability-quote-contract",
    "flutter_pkg": "capability_quote_contract",
    "route": "/quote-contract",
    "keywords": [
      "报价合同",
      "报价审批",
      "合同评审",
      "特价申请"
    ]
  },
  {
    "key": "rbac_page",
    "name": "角色权限",
    "category": "权限安全",
    "widget": "RBACWidget",
    "agent_id": "creation",
    "web_pkg": "@blockhub/web-capability-integration",
    "flutter_pkg": "capability_rbac_page",
    "route": "/rbac",
    "keywords": [
      "权限",
      "角色",
      "rbac",
      "可见范围"
    ]
  },
  {
    "key": "regulatory_report",
    "name": "监管报送",
    "category": "金融服务",
    "widget": "RegulatoryReportWidget",
    "agent_id": "regulatory_report",
    "web_pkg": "@blockhub/web-capability-finance",
    "flutter_pkg": "capability_finance",
    "route": "/regulatory-report",
    "keywords": [
      "监管报送",
      "报送",
      "监管报表",
      "合规报送"
    ]
  },
  {
    "key": "report_scheduled",
    "name": "定时报表",
    "category": "知识数据",
    "widget": "DashboardWidget",
    "agent_id": "report",
    "web_pkg": "@blockhub/web-capability-dashboard",
    "flutter_pkg": "capability_report_scheduled",
    "route": "/dashboard",
    "keywords": []
  },
  {
    "key": "route_task",
    "name": "路线任务",
    "category": "物流仓储",
    "widget": "RouteTaskWidget",
    "agent_id": "route_task",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/route-task",
    "keywords": [
      "路线",
      "配送路线",
      "站点顺序",
      "路线优化"
    ]
  },
  {
    "key": "sales_lead",
    "name": "销售获客",
    "category": "销售行业",
    "widget": "SalesLeadWidget",
    "agent_id": "sales_lead",
    "web_pkg": "@blockhub/web-capability-sales-lead",
    "flutter_pkg": "capability_sales_lead",
    "route": "/sales-lead",
    "keywords": [
      "销售获客",
      "销售线索",
      "客户跟进",
      "线索录入",
      "公海",
      "渠道来源",
      "销售漏斗"
    ]
  },
  {
    "key": "schedule_alarm",
    "name": "定时闹钟",
    "category": "Flutter工具",
    "widget": "AlarmWidget",
    "agent_id": "notify",
    "web_pkg": "",
    "flutter_pkg": "capability_schedule_alarm",
    "route": "/schedule-alarm",
    "keywords": [
      "闹钟",
      "alarm",
      "定时",
      "cron",
      "准时",
      "每天",
      "重复提醒",
      "番茄钟",
      "计时器",
      "倒计时"
    ]
  },
  {
    "key": "school_notice",
    "name": "家校通知",
    "category": "教育培训",
    "widget": "SchoolNoticeWidget",
    "agent_id": "school_notice",
    "web_pkg": "@blockhub/web-capability-school-notice",
    "flutter_pkg": "capability_school_notice",
    "route": "/school-notice",
    "keywords": [
      "家校通知",
      "家校",
      "活动报名",
      "家长留言",
      "学校通知"
    ]
  },
  {
    "key": "seal_request",
    "name": "用印申请",
    "category": "人事行政",
    "widget": "FormWidget",
    "agent_id": "approval",
    "web_pkg": "@blockhub/web-capability-approval",
    "flutter_pkg": "capability_seal_request",
    "route": "/seal-request",
    "keywords": [
      "用印",
      "盖章",
      "签章",
      "合同章",
      "公章"
    ]
  },
  {
    "key": "security_mask",
    "name": "数据脱敏展示",
    "category": "权限安全",
    "widget": "MaskWidget",
    "agent_id": "creation",
    "web_pkg": "@blockhub/web-capability-security-mask",
    "flutter_pkg": "capability_security_mask",
    "route": "/security-mask",
    "keywords": []
  },
  {
    "key": "shanghai_voice",
    "name": "上海话语音交互",
    "category": "智能交互",
    "widget": "ShanghaiVoiceWidget",
    "agent_id": "shanghai_voice",
    "web_pkg": "@blockhub/web-capability-voice",
    "flutter_pkg": "capability_shanghai_voice",
    "route": "/voice",
    "keywords": [
      "上海话",
      "语音助手",
      "方言",
      "实时语音",
      "麦克风"
    ]
  },
  {
    "key": "shanghai_voice_stream",
    "name": "实时语音流",
    "category": "智能交互",
    "widget": "VoiceStreamWidget",
    "agent_id": "shanghai_voice",
    "web_pkg": "@blockhub/web-capability-voice",
    "flutter_pkg": "capability_shanghai_voice_stream",
    "route": "/voice",
    "keywords": [
      "语音流",
      "asr",
      "tts",
      "websocket"
    ]
  },
  {
    "key": "shift_attendance",
    "name": "排班考勤",
    "category": "人事管理",
    "widget": "ShiftAttendanceWidget",
    "agent_id": "shift_attendance",
    "web_pkg": "@blockhub/web-capability-mfg-ops",
    "flutter_pkg": "capability_shift_attendance",
    "route": "/shift-attendance",
    "keywords": [
      "排班",
      "考勤",
      "班次",
      "打卡申诉"
    ]
  },
  {
    "key": "site_patrol",
    "name": "巡检打卡",
    "category": "现场运维",
    "widget": "SitePatrolWidget",
    "agent_id": "site_patrol",
    "web_pkg": "@blockhub/web-capability-site-patrol",
    "flutter_pkg": "capability_site_patrol",
    "route": "/site-patrol",
    "keywords": [
      "巡检打卡",
      "巡检",
      "打卡",
      "隐患",
      "安全巡检",
      "设备巡检"
    ]
  },
  {
    "key": "study_coach",
    "name": "课本学习",
    "category": "教育培训",
    "widget": "StudyCoachWidget",
    "agent_id": "study_coach",
    "web_pkg": "@blockhub/web-capability-study-coach",
    "flutter_pkg": "capability_study_coach",
    "route": "/study-coach",
    "keywords": [
      "课本学习",
      "今晚练什么",
      "听写",
      "单词卡",
      "学习规划",
      "家默",
      "复习跟进",
      "考试",
      "课本"
    ]
  },
  {
    "key": "training_record",
    "name": "技能培训",
    "category": "人事管理",
    "widget": "TrainingRecordWidget",
    "agent_id": "training_record",
    "web_pkg": "@blockhub/web-capability-mfg-ops",
    "flutter_pkg": "capability_training_record",
    "route": "/training-record",
    "keywords": [
      "培训",
      "上岗证",
      "技能档案",
      "复训"
    ]
  },
  {
    "key": "travel_plan",
    "name": "旅行攻略",
    "category": "生活服务",
    "widget": "TravelPlanWidget",
    "agent_id": "travel_plan",
    "web_pkg": "@blockhub/web-capability-travel-plan",
    "flutter_pkg": "capability_travel_plan",
    "route": "/travel-plan",
    "keywords": [
      "旅行攻略",
      "行程规划",
      "景点问答",
      "预订提醒",
      "旅行"
    ]
  },
  {
    "key": "warehouse_inbound",
    "name": "入库验收",
    "category": "物流仓储",
    "widget": "WarehouseInboundWidget",
    "agent_id": "warehouse_inbound",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/warehouse-inbound",
    "keywords": [
      "入库",
      "收货",
      "上架",
      "到货验收",
      "退货入库"
    ]
  },
  {
    "key": "warehouse_outbound",
    "name": "出库拣配",
    "category": "物流仓储",
    "widget": "WarehouseOutboundWidget",
    "agent_id": "warehouse_outbound",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/warehouse-outbound",
    "keywords": [
      "出库",
      "拣货",
      "波次",
      "复核出库"
    ]
  },
  {
    "key": "waybill_track",
    "name": "运单跟踪",
    "category": "物流仓储",
    "widget": "WaybillTrackWidget",
    "agent_id": "waybill_track",
    "web_pkg": "@blockhub/web-capability-logistics-ops",
    "flutter_pkg": "capability_logistics",
    "route": "/waybill-track",
    "keywords": [
      "运单",
      "在途",
      "干线",
      "城配",
      "物流跟踪"
    ]
  },
  {
    "key": "wedding_plan",
    "name": "婚礼筹备",
    "category": "生活服务",
    "widget": "WeddingPlanWidget",
    "agent_id": "wedding_plan",
    "web_pkg": "@blockhub/web-capability-wedding-plan",
    "flutter_pkg": "capability_wedding_plan",
    "route": "/wedding-plan",
    "keywords": [
      "婚礼筹备",
      "宾客名单",
      "供应商协同",
      "婚礼预算",
      "婚庆"
    ]
  }
] as const
