#!/usr/bin/env python3
"""Generate shared/capability-manifest.json from capability_registry.py."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.data.capability_registry import ALL_CAPABILITIES  # noqa: E402
from app.services.build_manifest import _route_for, _web_pkg, _flutter_pkg


def main() -> None:
    items = []
    for key in sorted(ALL_CAPABILITIES.keys()):
        cap = ALL_CAPABILITIES[key]
        items.append(
            {
                "key": cap.key,
                "name": cap.name,
                "category": cap.category,
                "widget": cap.widget,
                "agent_id": cap.agent_id,
                "web_pkg": _web_pkg(cap.key),
                "flutter_pkg": _flutter_pkg(cap.key),
                "route": _route_for(cap.key, cap.widget),
                "keywords": list(cap.keywords),
            }
        )
    out = ROOT / "shared" / "capability-manifest.json"
    out.write_text(json.dumps({"version": 1, "capabilities": items}, ensure_ascii=False, indent=2), encoding="utf-8")
    ts_lines = [
        "/** Auto-generated by scripts/codegen-capability-manifest.py — do not edit */",
        "export interface CapabilityManifestEntry {",
        "  key: string",
        "  name: string",
        "  category: string",
        "  widget: string",
        "  agent_id: string",
        "  web_pkg: string",
        "  flutter_pkg: string",
        "  route: string",
        "  keywords: string[]",
        "}",
        "export const CAPABILITY_MANIFEST: CapabilityManifestEntry[] = "
        + json.dumps(items, ensure_ascii=False, indent=2)
        + " as const",
        "",
    ]
    ts_out = ROOT / "shared" / "capability-manifest.ts"
    ts_out.write_text("\n".join(ts_lines), encoding="utf-8")
    print(f"wrote {out} ({len(items)} capabilities)")
    print(f"wrote {ts_out}")

    # ── Dart 产物：写入 Flutter 包，作为 App 端单一来源元数据 ──
    dart_out = ROOT / "runtime-app" / "lib" / "data" / "capability_manifest.dart"
    dart_out.parent.mkdir(parents=True, exist_ok=True)
    dart_out.write_text(_dart_source(items), encoding="utf-8")
    print(f"wrote {dart_out}")


def _dart_string(value) -> str:
    if value is None:
        return "null"
    return json.dumps(value, ensure_ascii=False)


def _dart_source(items: list[dict]) -> str:
    lines = [
        "// Auto-generated by scripts/codegen-capability-manifest.py — do not edit.",
        "class CapabilityManifestEntry {",
        "  final String key;",
        "  final String name;",
        "  final String category;",
        "  final String widget;",
        "  final String agentId;",
        "  final String? webPkg;",
        "  final String flutterPkg;",
        "  final String route;",
        "  final List<String> keywords;",
        "",
        "  const CapabilityManifestEntry({",
        "    required this.key,",
        "    required this.name,",
        "    required this.category,",
        "    required this.widget,",
        "    required this.agentId,",
        "    required this.webPkg,",
        "    required this.flutterPkg,",
        "    required this.route,",
        "    required this.keywords,",
        "  });",
        "}",
        "",
        "const List<CapabilityManifestEntry> capabilityManifest = [",
    ]
    for it in items:
        lines.append("  CapabilityManifestEntry(")
        lines.append(f"    key: {_dart_string(it['key'])},")
        lines.append(f"    name: {_dart_string(it['name'])},")
        lines.append(f"    category: {_dart_string(it['category'])},")
        lines.append(f"    widget: {_dart_string(it['widget'])},")
        lines.append(f"    agentId: {_dart_string(it['agent_id'])},")
        lines.append(f"    webPkg: {_dart_string(it['web_pkg'])},")
        lines.append(f"    flutterPkg: {_dart_string(it['flutter_pkg'])},")
        lines.append(f"    route: {_dart_string(it['route'])},")
        lines.append(f"    keywords: {json.dumps(it['keywords'], ensure_ascii=False)},")
        lines.append("  ),")
    lines.append("];")
    lines.append("")
    lines.append("final Map<String, CapabilityManifestEntry> capabilityManifestByKey = {")
    lines.append("  for (final e in capabilityManifest) e.key: e,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
