#!/usr/bin/env python3
"""P1-2 · Sync runtime-app pubspec + melos registry from capability_keys / manifest."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "shared" / "flutter-parity-matrix.json"
PUBSPEC = ROOT / "runtime-app" / "pubspec.yaml"
REGISTRY_G = ROOT / "runtime-app" / "lib" / "melos_capability_registry.g.dart"


def _load_matrix() -> dict:
    return json.loads(MATRIX_PATH.read_text(encoding="utf-8"))


def _key_to_flutter(matrix: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for row in matrix.get("rows", []):
        fp = row.get("flutter_pkg")
        if not fp:
            continue
        for key in row.get("capability_keys") or []:
            out[key] = fp
    return out


def _package_meta(matrix: dict) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for row in matrix.get("rows", []):
        fp = row.get("flutter_pkg")
        if not fp or fp in out:
            continue
        out[fp] = {
            "module_class": row.get("module_class", ""),
            "dart_import": row.get("dart_import", ""),
        }
    return out


def _keys_from_spec(spec_path: Path) -> list[str]:
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    keys = spec.get("capability_keys") or []
    if keys:
        return [str(k) for k in keys if k]
    manifest = spec.get("build_manifest") or {}
    return [str(k) for k in (manifest.get("capability_keys") or []) if k]


def resolve_flutter_packages(keys: list[str], matrix: dict) -> list[str]:
    key_map = _key_to_flutter(matrix)
    pkgs: list[str] = ["blockhub_flutter_core"]

    def _add(fp: str | None) -> None:
        if not fp or fp in pkgs:
            return
        if (ROOT / "packages" / fp / "pubspec.yaml").is_file():
            pkgs.append(fp)

    for key in keys:
        _add(key_map.get(key))
        if key not in key_map:
            _add(f"capability_{key}")

    if len(pkgs) == 1 and not keys:
        for row in matrix.get("rows", []):
            _add(row.get("flutter_pkg"))
    return pkgs


def _capability_dep_lines(packages: list[str]) -> list[str]:
    lines = ["  blockhub_flutter_core:", "    path: ../packages/blockhub_flutter_core"]
    for pkg in packages:
        if pkg == "blockhub_flutter_core":
            continue
        lines.append(f"  {pkg}:")
        lines.append(f"    path: ../packages/{pkg}")
    return lines


def patch_pubspec(packages: list[str], *, dry_run: bool = False) -> str:
    text = PUBSPEC.read_text(encoding="utf-8")
    cap_names = set()
    matrix = _load_matrix()
    for row in matrix.get("rows", []):
        if row.get("flutter_pkg"):
            cap_names.add(row["flutter_pkg"])
    cap_names.add("blockhub_flutter_core")

    # Remove existing capability path deps
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^  (blockhub_flutter_core|capability_[a-z0-9_]+):\s*$", line)
        if m and m.group(1) in cap_names:
            i += 1
            if i < len(lines) and lines[i].strip().startswith("path:"):
                i += 1
            continue
        out.append(line)
        i += 1

    # Insert capability deps after "dependencies:" and flutter sdk block
    inserted = False
    final: list[str] = []
    for idx, line in enumerate(out):
        final.append(line)
        if not inserted and line.strip() == "sdk: flutter":
            final.extend(_capability_dep_lines(packages))
            inserted = True
    if not inserted:
        raise RuntimeError("could not find insertion point in pubspec.yaml")

    new_text = "\n".join(final) + ("\n" if text.endswith("\n") else "")
    if not dry_run:
        PUBSPEC.write_text(new_text, encoding="utf-8")
    return new_text


def write_registry_g(packages: list[str], *, dry_run: bool = False) -> str:
    matrix = _load_matrix()
    meta = _package_meta(matrix)
    imports: list[str] = ["import 'package:blockhub_flutter_core/blockhub_flutter_core.dart';"]
    module_lines: list[str] = []
    seen_import: set[str] = set()

    for pkg in packages:
        if pkg == "blockhub_flutter_core":
            continue
        m = meta.get(pkg, {})
        dart_import = m.get("dart_import") or f"package:{pkg}/{pkg}.dart"
        module_class = m.get("module_class")
        if not module_class:
            continue
        if dart_import not in seen_import:
            imports.append(f"import '{dart_import}';")
            seen_import.add(dart_import)
        module_lines.append(f"  const {module_class}(),")

    body = "\n".join(
        [
            "// Auto-generated by scripts/flutter-sync-pubspec-from-manifest.py — do not edit.",
            *imports,
            "",
            "/// Manifest-selected Melos modules (build-time).",
            "List<CapabilityModule> get generatedMelosCapabilityModules => [",
            *module_lines,
            "];",
            "",
        ]
    )
    if not dry_run:
        REGISTRY_G.parent.mkdir(parents=True, exist_ok=True)
        REGISTRY_G.write_text(body, encoding="utf-8")
    return body


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync Flutter pubspec from capability keys")
    ap.add_argument("--keys", help="Comma-separated capability_keys")
    ap.add_argument("--spec", type=Path, help="Publish build queue JSON")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--skip-registry", action="store_true")
    args = ap.parse_args()

    if not MATRIX_PATH.is_file():
        print(f"ERROR: missing {MATRIX_PATH}", file=sys.stderr)
        return 1

    matrix = _load_matrix()
    if args.spec:
        keys = _keys_from_spec(args.spec)
    elif args.keys:
        keys = [k.strip() for k in args.keys.split(",") if k.strip()]
    else:
        keys = []

    packages = resolve_flutter_packages(keys, matrix)
    print("capability_keys:", keys or "<default present packages>")
    print("flutter_packages:", ", ".join(packages))

    if args.dry_run:
        print("\n--- pubspec capability deps ---")
        print("\n".join(_capability_dep_lines(packages)))
        if not args.skip_registry:
            print("\n--- melos_capability_registry.g.dart ---")
            print(write_registry_g(packages, dry_run=True))
        return 0

    patch_pubspec(packages, dry_run=False)
    print(f"wrote {PUBSPEC}")
    if not args.skip_registry:
        write_registry_g(packages, dry_run=False)
        print(f"wrote {REGISTRY_G}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
