#!/usr/bin/env python3
"""Build EN scene seeds for all packs still missing translations.

Uses longest-first phrase glossary + category map. Problems that remain CJK
get a short English closed-loop blurb from the EN name (no CN+EN mix).
Preserves existing seed entries (agriculture / med / hand overrides).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.data.industry_packs_all import ALL_INDUSTRY_PACKS  # noqa: E402

SEED = ROOT / "shared" / "i18n" / "seed" / "scene.en-US.json"
CAT_SEED = ROOT / "shared" / "i18n" / "seed" / "category.en-US.json"
CJK = re.compile(r"[\u4e00-\u9fff]")

# Longest-first. Prefer multi-char industry phrases over single chars.
_RAW_GLOSSARY: list[tuple[str, str]] = [
    ("自然语言查数", "NL data query"),
    ("自然语言问数", "natural-language query"),
    ("制度政策问答", "policy Q&A"),
    ("跨部门会签", "cross-dept countersign"),
    ("企微/钉钉推送", "WeCom/DingTalk push"),
    ("会议室预约", "meeting room booking"),
    ("不良事件上报", "adverse event report"),
    ("高警示药品核对", "high-alert med check"),
    ("院感巡查整改", "IPC round corrective action"),
    ("质控SOP检查", "QC SOP checklist"),
    ("医疗待办中心", "clinical todo hub"),
    ("院感预警推送", "IPC early-warning push"),
    ("手卫生抽查", "hand-hygiene spot check"),
    ("危急值通知", "critical-value notify"),
    ("危急值释义", "critical-value explainer"),
    ("抗菌药物问答", "antimicrobial Q&A"),
    ("继续教育题库", "CME question bank"),
    ("病例讨论纪要", "case-conference notes"),
    ("护理SOP检索", "nursing SOP lookup"),
    ("临床路径参考", "clinical pathway reference"),
    ("药品说明书问答", "drug insert Q&A"),
    ("诊疗指南检索", "guideline retrieval"),
    ("请假联动补位", "leave-linked backfill"),
    ("人力负荷看板", "staffing load board"),
    ("夜班交接清单", "night-shift handover list"),
    ("弹性排班", "flexible roster"),
    ("排班一览", "roster overview"),
    ("护士长审批", "charge-nurse approval"),
    ("调班冲突检测", "shift-swap conflict check"),
    ("儿科分诊分流", "pediatric triage routing"),
    ("红旗症状预警", "red-flag symptom alert"),
    ("过敏史采集", "allergy history capture"),
    ("主诉结构化", "chief-complaint structuring"),
    ("复诊预约引导", "follow-up booking guide"),
    ("导诊待办闭环", "triage todo closed loop"),
    ("急诊分诊辅助", "ED triage assist"),
    ("症状预问诊", "symptom pre-consult"),
    ("设备报修工单", "equipment repair ticket"),
    ("设备报修", "equipment repair"),
    ("保养计划执行", "PM plan execution"),
    ("点检标准查询", "inspection standard lookup"),
    ("备件更换记录", "spare-parts change log"),
    ("TPM活动记录", "TPM activity log"),
    ("生产日报", "production daily report"),
    ("停机原因记录", "downtime reason log"),
    ("换型时间记录", "changeover time log"),
    ("来料质检报告", "incoming QC report"),
    ("过程检SPC数据", "in-process SPC data"),
    ("不合格品评审单", "NCR review form"),
    ("客诉返工单", "customer-complaint rework"),
    ("成品检验报告", "finished-goods QC report"),
    ("领料登记", "material issue log"),
    ("退料登记", "material return log"),
    ("齐套检查", "kitting check"),
    ("超发预警配置", "over-issue alert config"),
    ("盘点录入", "inventory count entry"),
    ("隐患上报", "hazard report"),
    ("隐患整改闭环", "hazard corrective closed loop"),
    ("班前会记录", "pre-shift meeting log"),
    ("排班调整", "roster adjustment"),
    ("证书上传", "certificate upload"),
    ("SOP问答配置", "SOP Q&A config"),
    ("图纸BOM上传", "drawing/BOM upload"),
    ("MES工单同步配置", "MES work-order sync"),
    ("工艺变更培训记录", "process-change training log"),
    ("报工看板配置", "production board config"),
    ("线索录入", "lead intake"),
    ("线索分配", "lead assignment"),
    ("线索清洗", "lead cleansing"),
    ("公海领取", "public-pool claim"),
    ("线索评分", "lead scoring"),
    ("转介绍线索", "referral lead"),
    ("拜访纪要", "visit notes"),
    ("电话跟进", "call follow-up"),
    ("丢单记录", "lost-deal log"),
    ("赢单复盘", "won-deal review"),
    ("决策链节点", "buying-committee node"),
    ("标准报价", "standard quote"),
    ("特价折扣申请", "special-discount request"),
    ("方案报价", "solution quote"),
    ("竞标报价", "bid quote"),
    ("报价版本管理", "quote versioning"),
    ("交叉销售机会", "cross-sell opportunity"),
    ("销售合同审批", "sales contract approval"),
    ("合同变更申请", "contract change request"),
    ("回款计划登记", "collection plan log"),
    ("销售开票申请", "sales invoice request"),
    ("回款确认登记", "payment confirmation log"),
    ("销售漏斗分析", "sales funnel analytics"),
    ("业绩排行看板", "performance leaderboard"),
    ("提成核算查询", "commission query"),
    ("区域销售对比", "regional sales compare"),
    ("产品线销售分析", "product-line sales analytics"),
    ("销售预测填报", "sales forecast entry"),
    ("销售问数机器人", "sales NL query bot"),
    ("目标达成看板", "target attainment board"),
    ("外勤签到", "field check-in"),
    ("拜访路线规划", "visit route planning"),
    ("陪访登记", "joint-visit log"),
    ("门店巡访记录", "store visit log"),
    ("会销活动登记", "event campaign log"),
    ("客户招待申请", "client entertainment request"),
    ("联合拜访登记", "co-visit log"),
    ("福利政策咨询", "benefits policy consult"),
    ("员工手册问答", "employee handbook Q&A"),
    ("家校通知", "school-home notice"),
    ("作业答疑", "homework Q&A"),
    ("工作票签发", "work permit issue"),
    ("操作票管理", "switching order mgmt"),
    ("客房预订", "room reservation"),
    ("房态变更", "room-status change"),
    ("高处作业许可", "work-at-height permit"),
    ("诉求受理登记", "petition intake"),
    ("热线转办派单", "hotline transfer dispatch"),
    ("选题申报", "topic proposal"),
    ("采访提纲", "interview outline"),
    ("岗位发布", "job posting"),
    ("简历筛选", "resume screening"),
    ("立案登记", "case filing"),
    ("利益冲突检索", "conflict-of-interest search"),
    ("门店调拨", "store transfer"),
    ("损耗报损", "shrinkage write-off"),
    ("维保工单派发", "service-order dispatch"),
    ("预约进厂管理", "inbound appointment"),
    ("开户适当性", "account suitability"),
    ("投研尽调", "research due diligence"),
    ("对公开户 KYC", "corporate KYC onboarding"),
    ("零售开户 KYC", "retail KYC onboarding"),
    ("理赔受理", "claims intake"),
    ("代理人展业", "agent field sales"),
    ("看房预约", "showing appointment"),
    ("签约认购", "subscription signing"),
    ("风控预警", "risk alert"),
    ("贷后管理", "post-loan management"),
    ("入库验收", "inbound acceptance"),
    ("出库拣配", "outbound picking"),
    ("产品披露", "product disclosure"),
    ("投后管理", "post-investment management"),
    ("玩家FAQ", "player FAQ"),
    ("客服工单", "support ticket"),
    ("田间巡查记录", "field inspection log"),
    ("农事日历", "farming calendar"),
    ("知识库", "knowledge base"),
    ("知识问答", "knowledge Q&A"),
    ("制度文档库", "policy document library"),
    ("会议室", "meeting room"),
    ("审批提醒", "approval reminder"),
    ("公告通知", "announcement"),
    ("待办推送", "todo push"),
    ("邮件通知", "email notify"),
    ("账号权限", "account permissions"),
    ("资产领用", "asset checkout"),
    ("资产盘点", "asset inventory"),
    ("软件安装", "software install"),
    ("网络安全", "network security"),
    ("访客登记", "visitor registration"),
    ("单点登录", "SSO"),
    ("开放 API", "open API"),
    ("请假申请", "leave request"),
    ("加班申请", "overtime request"),
    ("出差申请", "travel request"),
    ("报销审批", "expense claim"),
    ("入职办理", "onboarding"),
    ("离职交接", "offboarding handover"),
    ("考勤异常", "attendance exception"),
    ("用章申请", "seal request"),
    ("用印申请", "seal request"),
    ("名片申请", "business card request"),
    ("福利申领", "benefits claim"),
    ("付款申请", "payment request"),
    ("采购申请", "purchase request"),
    ("合同审批", "contract approval"),
    ("预算追加", "budget top-up"),
    ("开票申请", "invoice request"),
    ("收款确认", "payment confirmation"),
    ("法务咨询", "legal consult"),
    ("会议纪要", "meeting minutes"),
    ("文档协作", "document collab"),
    ("培训资料", "training materials"),
    ("通用审批", "general approval"),
    ("请示报告", "request for instruction"),
    ("用印流程", "seal workflow"),
    ("变更申请", "change request"),
    ("经营看板", "ops dashboard"),
    ("人事报表", "HR reports"),
    ("费用分析", "expense analytics"),
    ("导出报表", "export reports"),
    ("费用报销", "expense reimbursement"),
    ("借款申请", "loan request"),
    ("合同电子签章", "contract e-sign"),
    ("发票核验", "invoice verification"),
    ("多级会签", "multi-level countersign"),
    ("代理审批设置", "proxy approval setup"),
    ("条件分支审批", "conditional approval"),
    ("IT报障", "IT incident"),
    ("IT 报修", "IT repair ticket"),
    ("库存预警", "inventory alert"),
    ("库存盘点", "stocktake"),
    ("供应商对账", "supplier reconciliation"),
    ("订单跟踪", "order tracking"),
    ("全渠道自提", "omnichannel pickup"),
    ("外卖履约", "delivery fulfillment"),
    ("电商仅退款", "e-commerce refund-only"),
    ("退换货", "return & exchange"),
    ("小票稽核", "receipt audit"),
    ("收银异常", "POS exception"),
    ("陈列检查", "display check"),
    ("补货上架", "replenishment shelving"),
    ("门店巡检", "store inspection"),
    ("价格变更", "price change"),
    ("新品上架", "new-item listing"),
    ("竞品采价", "competitor price check"),
    ("优惠券核销", "coupon redemption"),
    ("储值卡充值", "stored-value top-up"),
    ("会员预留", "member reservation"),
    ("会员营销", "member marketing"),
    ("促销活动", "promotion campaign"),
    ("运单跟踪", "shipment tracking"),
    ("仓储盘点", "warehouse stocktake"),
    ("调度派车", "fleet dispatch"),
    ("签收回单", "POD confirmation"),
    ("异常上报", "exception report"),
    ("冷链监控", "cold-chain monitoring"),
    ("看房回访", "showing follow-up"),
    ("物业报修", "property repair"),
    ("租金收缴", "rent collection"),
    ("客户跟进", "customer follow-up"),
    ("房源上架", "listing publish"),
    ("装修验收", "fit-out acceptance"),
    ("业主投诉", "owner complaint"),
    ("租约续签", "lease renewal"),
    ("物业费催缴", "HOA fee chase"),
    ("中介佣金", "broker commission"),
    ("交房验收", "handover acceptance"),
    ("动火票审批", "hot-work permit approval"),
    ("许可开工确认", "permit-to-work confirm"),
    ("工作票终结", "work permit closeout"),
    ("缺陷登记", "defect log"),
    ("隐患分级", "hazard grading"),
    ("整改闭环", "corrective closed loop"),
    ("重复缺陷分析", "repeat-defect analysis"),
    ("安环拍图", "HSE photo report"),
    ("线路巡检打卡", "line patrol check-in"),
    ("变电站点检记录", "substation inspection log"),
    ("无人机巡视报告", "UAV inspection report"),
    ("测温异常登记", "temp-anomaly log"),
    ("表计抄录台账", "meter reading ledger"),
    ("计划停电通知", "planned outage notice"),
    ("故障抢修派工单", "fault repair dispatch"),
    ("复电确认", "re-energize confirm"),
    ("保电任务", "power-assurance task"),
    ("备件领用申请", "spare checkout request"),
    ("备件归还登记", "spare return log"),
    ("碳排放数据填报", "carbon emission entry"),
    ("油耗台账记录", "fuel ledger log"),
    ("调度令执行记录", "dispatch-order execution"),
    ("接地线装拆记录", "earthing lead log"),
    ("反措任务单", "corrective-measure task"),
    ("应急演练记录", "emergency drill log"),
    ("网格事件上报", "grid event report"),
    ("矛盾调解记录", "dispute mediation log"),
    ("巡查打卡", "patrol check-in"),
    ("人口信息核查", "population info verify"),
    ("证照申领预审", "license pre-review"),
    ("补正告知通知", "supplement notice"),
    ("办件进度查询", "case progress query"),
    ("许可证变更审批", "permit change approval"),
    ("证照年检提醒", "license annual reminder"),
    ("预约取号", "appointment ticket"),
    ("一件事一次办申请", "one-stop service request"),
    ("应急事件登记", "emergency event log"),
    ("信息公开申请表", "info disclosure request"),
    ("舆情信息报送", "public-opinion report"),
    ("数据共享申请表", "data-sharing request"),
    ("催办督办管理", "chase & supervise"),
    ("满意度回访记录", "satisfaction callback log"),
    ("重复诉求合并", "duplicate petition merge"),
    ("紧急工单标记", "urgent ticket flag"),
    ("知识库", "knowledge base"),
    ("审批", "approval"),
    ("请假", "leave"),
    ("加班", "overtime"),
    ("出差", "travel"),
    ("报销", "expense"),
    ("入职", "onboarding"),
    ("离职", "offboarding"),
    ("考勤", "attendance"),
    ("用章", "seal"),
    ("用印", "seal"),
    ("名片", "business card"),
    ("福利", "benefits"),
    ("付款", "payment"),
    ("采购", "purchase"),
    ("合同", "contract"),
    ("预算", "budget"),
    ("开票", "invoicing"),
    ("收款", "collections"),
    ("法务", "legal"),
    ("制度", "policy"),
    ("会议", "meeting"),
    ("培训", "training"),
    ("报表", "report"),
    ("看板", "dashboard"),
    ("公告", "announcement"),
    ("通知", "notification"),
    ("待办", "todo"),
    ("邮件", "email"),
    ("报修", "repair ticket"),
    ("权限", "permissions"),
    ("资产", "assets"),
    ("访客", "visitor"),
    ("对接", "integration"),
    ("同步", "sync"),
    ("申请", "request"),
    ("办理", "processing"),
    ("交接", "handover"),
    ("异常", "exception"),
    ("预约", "booking"),
    ("确认", "confirmation"),
    ("咨询", "consult"),
    ("文档", "document"),
    ("协作", "collab"),
    ("资料", "materials"),
    ("通用", "general"),
    ("请示", "escalation"),
    ("报告", "report"),
    ("流程", "workflow"),
    ("变更", "change"),
    ("经营", "operations"),
    ("人事", "HR"),
    ("费用", "expense"),
    ("分析", "analytics"),
    ("导出", "export"),
    ("提醒", "reminder"),
    ("推送", "push"),
    ("账号", "account"),
    ("领用", "checkout"),
    ("软件", "software"),
    ("安装", "install"),
    ("网络", "network"),
    ("安全", "security"),
    ("登记", "registration"),
    ("开放", "open"),
    ("线索", "lead"),
    ("报价", "quote"),
    ("漏斗", "funnel"),
    ("客户", "customer"),
    ("会员", "member"),
    ("库存", "inventory"),
    ("订单", "order"),
    ("运单", "shipment"),
    ("仓储", "warehouse"),
    ("调度", "dispatch"),
    ("签收", "POD"),
    ("排班", "scheduling"),
    ("导诊", "triage"),
    ("质检", "QC"),
    ("巡检", "inspection"),
    ("工单", "work order"),
    ("理赔", "claims"),
    ("核保", "underwriting"),
    ("招聘", "recruiting"),
    ("绩效", "performance"),
    ("薪酬", "payroll"),
    ("活动", "campaign"),
    ("内容", "content"),
    ("审核", "review"),
    ("版权", "copyright"),
    ("分发", "distribution"),
    ("试驾", "test drive"),
    ("售后", "aftersales"),
    ("配件", "parts"),
    ("进度", "progress"),
    ("材料", "materials"),
    ("验收", "acceptance"),
    ("溯源", "traceability"),
    ("补贴", "subsidy"),
    ("产销", "sales"),
    ("选题", "topic planning"),
    ("管理", "mgmt"),
    ("服务", "service"),
    ("查询", "query"),
    ("跟踪", "tracking"),
    ("预警", "alert"),
    ("监控", "monitoring"),
    ("配置", "config"),
    ("智能", "smart"),
    ("在线", "online"),
    ("标准", "standard"),
    ("场景", "scene"),
    ("记录", "log"),
    ("台账", "ledger"),
    ("看板", "board"),
    ("审批", "approval"),
    ("填报", "entry"),
    ("申报", "filing"),
    ("派单", "dispatch"),
    ("派工", "dispatch"),
    ("闭环", "closed loop"),
    ("整改", "corrective action"),
    ("巡查", "patrol"),
    ("点检", "spot check"),
    ("维保", "maintenance"),
    ("计量", "metrology"),
    ("灭菌", "sterilization"),
    ("会诊", "consult"),
    ("手术", "surgery"),
    ("床位", "bed"),
    ("输血", "transfusion"),
    ("耗材", "consumables"),
    ("设备", "equipment"),
    ("科室", "department"),
    ("门诊", "outpatient"),
    ("住院", "inpatient"),
    ("患者", "patient"),
    ("护士", "nurse"),
    ("医生", "doctor"),
    ("门店", "store"),
    ("仓库", "warehouse"),
    ("物流", "logistics"),
    ("冷链", "cold chain"),
    ("房源", "listing"),
    ("业主", "owner"),
    ("租约", "lease"),
    ("租金", "rent"),
    ("装修", "fit-out"),
    ("交房", "handover"),
    ("看房", "showing"),
    ("签约", "signing"),
    ("认购", "subscription"),
    ("开户", "account opening"),
    ("KYC", "KYC"),
    ("尽调", "due diligence"),
    ("披露", "disclosure"),
    ("投后", "post-investment"),
    ("贷后", "post-loan"),
    ("风控", "risk control"),
    ("催收", "collections"),
    ("监管", "regulatory"),
    ("报送", "filing"),
    ("代理人", "agent"),
    ("展业", "field sales"),
    ("核保", "underwriting"),
    ("理赔", "claims"),
    ("保单", "policy"),
    ("投研", "research"),
    ("适当性", "suitability"),
    ("合规", "compliance"),
    ("隐私", "privacy"),
    ("脱敏", "masking"),
    ("权限", "RBAC"),
    ("角色", "role"),
    ("同步", "sync"),
    ("推送", "push"),
    ("预警", "alert"),
    ("看板", "dashboard"),
    ("趋势", "trend"),
    ("分析", "analytics"),
    ("概览", "overview"),
    ("问答", "Q&A"),
    ("检索", "lookup"),
    ("采集", "capture"),
    ("结构化", "structuring"),
    ("分流", "routing"),
    ("引导", "guide"),
    ("辅助", "assist"),
    ("预问诊", "pre-consult"),
    ("分诊", "triage"),
    ("排班", "roster"),
    ("调班", "shift swap"),
    ("补位", "backfill"),
    ("负荷", "load"),
    ("交接", "handover"),
    ("清单", "checklist"),
    ("抽查", "spot check"),
    ("核对", "double-check"),
    ("追溯", "trace"),
    ("申购", "purchase request"),
    ("到期", "due"),
    ("占用", "occupancy"),
    ("周转", "turnover"),
    ("预测", "forecast"),
    ("对比", "compare"),
    ("排行", "ranking"),
    ("提成", "commission"),
    ("漏斗", "funnel"),
    ("商机", "opportunity"),
    ("报价", "quote"),
    ("合同", "contract"),
    ("回款", "collections"),
    ("开票", "invoicing"),
    ("拜访", "visit"),
    ("跟进", "follow-up"),
    ("公海", "public pool"),
    ("清洗", "cleansing"),
    ("评分", "scoring"),
    ("分配", "assignment"),
    ("录入", "intake"),
    ("发布", "publish"),
    ("筛选", "screening"),
    ("面试", "interview"),
    ("转正", "conversion"),
    ("绩效", "performance"),
    ("培训", "training"),
    ("签到", "check-in"),
    ("考试", "exam"),
    ("编制", "headcount"),
    ("异动", "transfer"),
    ("晋升", "promotion"),
    ("薪酬", "payroll"),
    ("社保", "social insurance"),
    ("公积金", "housing fund"),
    ("续签", "renewal"),
    ("竞业", "non-compete"),
    ("立案", "filing"),
    ("管辖", "jurisdiction"),
    ("保全", "preservation"),
    ("证据", "evidence"),
    ("鉴定", "appraisal"),
    ("开庭", "hearing"),
    ("延期", "extension"),
    ("选题", "topic"),
    ("采访", "interview"),
    ("审核", "review"),
    ("成片", "final cut"),
    ("版权", "copyright"),
    ("字幕", "subtitles"),
    ("封面", "cover"),
    ("敏感词", "sensitive words"),
    ("肖像", "likeness"),
    ("广告法", "ad-law"),
    ("分发", "distribution"),
    ("场控", "floor control"),
    ("评论", "comments"),
    ("置顶", "pin"),
    ("下架", "takedown"),
    ("刊例", "rate card"),
    ("舆情", "public opinion"),
    ("品牌", "brand"),
    ("维保", "maintenance"),
    ("进厂", "inbound"),
    ("质检交车", "QC vehicle handover"),
    ("配件入库", "parts inbound"),
    ("缺件订货", "backorder request"),
    ("旧件回收", "old-parts reclaim"),
    ("索赔件", "warranty part"),
    ("盘点差异", "count variance"),
    ("出车任务", "dispatch trip"),
    ("里程油耗", "mileage & fuel"),
    ("违章", "traffic violation"),
    ("事故上报", "accident report"),
    ("试驾", "test drive"),
    ("二手车评估", "used-car appraisal"),
    ("充电桩", "EV charger"),
    ("保险续保", "insurance renewal"),
    ("事故定损", "loss assessment"),
    ("代步车", "courtesy car"),
    ("作业答疑", "homework Q&A"),
    ("家校", "school-home"),
    ("课程", "course"),
    ("题库", "question bank"),
    ("排课", "class scheduling"),
    ("招生", "enrollment"),
    ("学员", "student"),
    ("教室", "classroom"),
    ("客房", "guest room"),
    ("房态", "room status"),
    ("预订", "reservation"),
    ("入住", "check-in"),
    ("退房", "check-out"),
    ("餐饮", "F&B"),
    ("班次", "shift"),
    ("投诉", "complaint"),
    ("巡检", "inspection"),
    ("高处作业", "work at height"),
    ("临边防护", "edge protection"),
    ("安全交底", "safety briefing"),
    ("事故快报", "incident flash report"),
    ("材料进场", "material intake"),
    ("隐蔽工程", "concealed works"),
    ("检验批", "inspection lot"),
    ("实测实量", "as-built measurement"),
    ("不合格品", "nonconforming item"),
    ("形象进度", "visual progress"),
    ("工程签证", "engineering VO"),
    ("变更洽商", "change negotiation"),
    ("劳务人员", "labor crew"),
    ("材料调拨", "material transfer"),
    ("机械进出场", "machinery in/out"),
    ("分包结算", "subcontract settlement"),
    ("周转材", "formwork turnover"),
    ("图纸会审", "drawing review"),
    ("技术交底", "tech briefing"),
    ("设计变更", "design change"),
    ("竣工资料", "as-built docs"),
    ("竣工验收", "final acceptance"),
    ("消缺整改", "punch-list fix"),
    ("保修回访", "warranty callback"),
    ("结算争议", "settlement dispute"),
]

GLOSSARY = sorted(_RAW_GLOSSARY, key=lambda pair: (-len(pair[0]), pair[0]))

# Exact leftovers after glossary (full scene titles that still fail tokenizing).
EXACT_NAME_EN: dict[str, str] = {
    "迷你吧计费": "Minibar billing",
    "礼宾需求": "Concierge request",
    "失物招领": "Lost & found",
    "客诉处理": "Guest complaint handling",
    "餐厅订位": "Restaurant reservation",
    "菜品沽清": "Menu 86 / sold-out",
    "厨余报损": "Kitchen waste write-off",
    "卫生检查": "Hygiene inspection",
    "营收日报": "Revenue daily report",
    "渠道归因": "Channel attribution",
    "会销报名": "Event registration",
    "复盘纪要归档": "Retro notes archive",
    "券包发放任务": "Coupon-pack issuance",
    "沉默唤醒计划": "Win-back dormant customers",
    "企微社群触达": "WeCom community outreach",
    "生日关怀自动化": "Birthday care automation",
    "竞品价格追踪": "Competitor price tracking",
    "丢单原因": "Lost-deal reasons",
    "决策链": "Decision chain",
    "特价折扣": "Special discount",
    "交叉销售": "Cross-sell",
    "产品话术库": "Product talk-track library",
    "成功案例库": "Success-case library",
    "解决方案库": "Solution playbook library",
    "作业完成率统计": "Homework completion stats",
    "学期校历": "Semester calendar",
    "课本学习": "Textbook learning",
    "家默督导": "Home study coaching",
    "错题本": "Wrong-answer notebook",
    "听课评课反馈": "Class observation feedback",
    "目标制定": "Goal setting",
    "内训讲师库": "Internal trainer roster",
    "薪资异议申诉": "Payroll dispute appeal",
    "九宫格盘点": "9-box talent review",
    "关键岗位继任": "Key-role succession",
    "路线任务派发": "Route task dispatch",
    "运费结算": "Freight settlement",
    "装卸排队": "Loading dock queue",
    "末端配送单": "Last-mile delivery order",
    "退货入库": "Return-to-stock",
    "保险产品说明": "Insurance product brief",
    "续期保费催缴": "Renewal premium chase",
    "再保分出结算": "Reinsurance cession settlement",
    "个险佣金结算": "Individual-life commission settlement",
    "最佳实践库": "Best-practice library",
    "超时催办": "Timeout chase",
    "条件分支": "Conditional branch",
    "订阅消息": "Subscription messages",
    "反洗钱监测": "AML monitoring",
    "普惠小微贷前调查": "Inclusive MSME pre-loan survey",
    "运营日报自动生成": "Ops daily report auto-gen",
    "交易对手准入": "Counterparty onboarding",
    "反洗钱筛查": "AML screening",
    "尽职调查问卷": "Due-diligence questionnaire",
    "当事人建档": "Party intake filing",
    "条款风险点": "Clause risk points",
    "律师函": "Lawyer's letter",
    "换型时间统计": "Changeover time stats",
    "盘点任务": "Inventory count task",
    "隐患随手拍": "Hazard snap reporting",
    "影响户数统计": "Affected-household count",
    "场站应急演练": "Site emergency drill",
    "一件事一次办": "One-stop one-trip service",
    "证照电子亮证": "Digital license display",
    "事故快速上报": "Rapid incident report",
    "关键节点管控": "Critical-path control",
    "联合贷对账": "Co-lending reconciliation",
    "公会举报处理": "Guild report handling",
    "角本大纲": "Script outline",
    "产品销售说明": "Product sales brief",
}

EXACT_CAT_EN: dict[str, str] = {
    "两票三制": "Two-ticket three-system",
    "两融": "Margin trading",
    "个险": "Individual life",
    "中后台": "Middle & back office",
    "交易运营": "Trading ops",
    "产品设计": "Product design",
    "人才盘点": "Talent review",
    "估值": "Valuation",
    "信用卡": "Credit card",
    "信贷业务": "Credit business",
    "停电抢修": "Outage repair",
    "健康险": "Health insurance",
    "充电年检": "Charging & annual inspection",
    "全渠道履约": "Omnichannel fulfillment",
    "再保": "Reinsurance",
    "劳务物资": "Labor & materials",
    "反欺诈": "Anti-fraud",
    "同业": "Interbank",
    "团险": "Group insurance",
    "图纸交底": "Drawing handover",
    "基层数据": "Grassroots data",
    "外勤协同": "Field collab",
    "学业评估": "Academic assessment",
    "学籍财务": "Enrollment & billing",
    "安环班组": "HSE crews",
    "审计": "Audit",
    "客服": "Customer service",
    "对公": "Corporate banking",
    "对公业务": "Corporate business",
    "工艺集成": "Process integration",
    "师资教研": "Faculty & teaching research",
    "应急公开": "Emergency disclosure",
    "投行业务": "IB business",
    "投行承销": "IB underwriting",
    "教学互动": "Teaching interaction",
    "普惠小微": "Inclusive MSME",
    "末端配送": "Last-mile delivery",
    "法规知识": "Regulatory knowledge",
    "清算": "Clearing",
    "物资双碳": "Materials & dual-carbon",
    "现场安监": "On-site HSE",
    "研究所": "Research institute",
    "竞品监测": "Competitor monitoring",
    "竣工收尾": "Handover closeout",
    "精算协同": "Actuarial collab",
    "系统集成": "System integration",
    "经纪": "Brokerage",
    "续期": "Renewal",
    "缺陷隐患": "Defects & hazards",
    "网格治理": "Grid governance",
    "联合贷": "Co-lending",
    "获客": "Acquisition",
    "诉求热线": "Service hotline",
    "诉讼排期": "Litigation calendar",
    "财富": "Wealth",
    "车队运营": "Fleet ops",
    "车险": "Auto insurance",
    "运营": "Operations",
    "运营互动": "Ops engagement",
    "销售赋能": "Sales enablement",
    "零售": "Retail",
    "零售业务": "Retail business",
}


def glossary_en(text: str) -> str:
    if not text:
        return text
    exact = EXACT_NAME_EN.get(text.strip())
    if exact:
        return exact
    remaining = text
    parts: list[str] = []
    while remaining:
        hit = None
        for zh, en in GLOSSARY:
            if remaining.startswith(zh):
                hit = (zh, en)
                break
        if hit:
            parts.append(hit[1])
            remaining = remaining[len(hit[0]) :]
            continue
        m = re.match(r"^[\dA-Za-z+/·\-_\s]+", remaining)
        if m:
            tok = m.group(0).strip()
            if tok:
                parts.append(tok)
            remaining = remaining[m.end() :]
            continue
        # Unknown CJK — skip char rather than emit spaced junk
        remaining = remaining[1:]
    out = " ".join(p for p in parts if p).strip()
    out = re.sub(r"\s+", " ", out)
    if not out or CJK.search(out):
        return ""
    return out[:1].upper() + out[1:]


def load_json(path: Path) -> dict:
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8-sig"))


def main() -> None:
    seed = {k: v for k, v in load_json(SEED).items() if not str(k).startswith("_")}
    cats = {k: v for k, v in load_json(CAT_SEED).items() if not str(k).startswith("_")}
    added = 0
    cat_added = 0

    for pack in ALL_INDUSTRY_PACKS:
        key = pack["key"]
        for i, scene in enumerate(pack.get("scenes") or [], start=1):
            idx = f"{i:03d}"
            nkey = f"scene.{key}.{idx}.name"
            pkey = f"scene.{key}.{idx}.problem"
            ckey = f"scene.{key}.{idx}.category"
            name = scene.get("name") or f"{key}-{idx}"
            problem = scene.get("problem") or name
            category = scene.get("category") or ""

            if category and (category not in cats or CJK.search(str(cats.get(category, "")))):
                en_cat = EXACT_CAT_EN.get(category) or glossary_en(category)
                if en_cat and not CJK.search(en_cat):
                    cats[category] = en_cat
                    cat_added += 1

            if nkey not in seed or CJK.search(str(seed.get(nkey, ""))):
                en_name = EXACT_NAME_EN.get(name) or glossary_en(name)
                if en_name:
                    seed[nkey] = en_name
                    added += 1
                # else leave missing — codegen keeps zh parity

            en_name = seed.get(nkey) or EXACT_NAME_EN.get(name) or glossary_en(name) or name
            if pkey not in seed or CJK.search(str(seed.get(pkey, ""))):
                if en_name and not CJK.search(str(en_name)):
                    seed[pkey] = f"{en_name}: typical industry closed-loop scenario."
                    added += 1

            if ckey not in seed or CJK.search(str(seed.get(ckey, ""))):
                en_cat = cats.get(category) or EXACT_CAT_EN.get(category) or glossary_en(category)
                if en_cat and not CJK.search(en_cat):
                    seed[ckey] = en_cat
                    added += 1

    out = {"_comment": "Hand + glossary seeds for scene.{pack}.{idx}.name|problem|category. Codegen prefers these."}
    out.update(dict(sorted(seed.items())))
    SEED.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    cat_out = {"_comment": "Chinese category → en-US."}
    cat_out.update(dict(sorted(cats.items())))
    CAT_SEED.write_text(json.dumps(cat_out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"OK seed keys={len(seed)} (+~{added} writes) categories={len(cats)} (+{cat_added})")


if __name__ == "__main__":
    main()
