import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter/widgets.dart';

/// Locale codes aligned with Web `@blockhub/i18n` (`zh-CN` | `en-US`).
typedef BhLocale = String;

/// BlockHub l10n — loads flat dotted keys from assets generated by
/// `scripts/codegen-flutter-arb.py` (same keys as Web messages / package locales).
class BhL10n extends ChangeNotifier {
  BhL10n._();

  static final BhL10n instance = BhL10n._();

  static const BhLocale zhCN = 'zh-CN';
  static const BhLocale enUS = 'en-US';
  static const List<Locale> supportedLocales = [
    Locale('zh', 'CN'),
    Locale('en', 'US'),
  ];

  BhLocale _locale = zhCN;
  final Map<BhLocale, Map<String, String>> _tables = {
    zhCN: {},
    enUS: {},
  };
  bool _loaded = false;

  BhLocale get locale => _locale;
  bool get isLoaded => _loaded;

  Locale get flutterLocale {
    if (_locale == enUS) return const Locale('en', 'US');
    return const Locale('zh', 'CN');
  }

  Future<void> load() async {
    for (final loc in [zhCN, enUS]) {
      final candidates = [
        'packages/blockhub_flutter_core/assets/i18n/$loc.json',
        'assets/i18n/$loc.json',
      ];
      var loaded = false;
      for (final path in candidates) {
        try {
          final raw = await rootBundle.loadString(path);
          final map = jsonDecode(raw) as Map<String, dynamic>;
          _tables[loc] = {
            for (final e in map.entries)
              if (e.value is String && !e.key.startsWith('_') && e.key != r'$schema')
                e.key: e.value as String,
          };
          loaded = true;
          break;
        } catch (_) {
          // try next path
        }
      }
      if (!loaded) {
        _tables[loc] = {};
      }
    }
    _loaded = true;
    notifyListeners();
  }

  void setLocale(BhLocale next) {
    if (next != zhCN && next != enUS) return;
    if (_locale == next) return;
    _locale = next;
    notifyListeners();
  }

  void setFlutterLocale(Locale locale) {
    final tag = '${locale.languageCode}-${locale.countryCode ?? ''}';
    if (tag.toLowerCase().startsWith('en')) {
      setLocale(enUS);
    } else {
      setLocale(zhCN);
    }
  }

  String t(String key, [Map<String, Object>? vars]) {
    final primary = _tables[_locale]?[key];
    final fallback = _tables[zhCN]?[key];
    final raw = primary ?? fallback ?? key;
    return interpolate(raw, vars);
  }

  /// Prefer translation; if missing, return [fallback] (mirrors Web `useTf`).
  String tf(String key, String fallback, [Map<String, Object>? vars]) {
    final text = t(key, vars);
    if (text == key) return interpolate(fallback, vars);
    return text;
  }

  static String interpolate(String template, Map<String, Object>? vars) {
    if (vars == null || vars.isEmpty) return template;
    var out = template;
    vars.forEach((k, v) {
      out = out.replaceAll('{{$k}}', '$v');
      out = out.replaceAll('{$k}', '$v');
    });
    return out;
  }

  /// Date formatting following active locale.
  String formatDate(DateTime date, {String? pattern}) {
    final loc = _locale == enUS ? 'en_US' : 'zh_CN';
    // Avoid hard dependency on package intl in core — use simple ISO-ish + locale separators.
    final y = date.year.toString().padLeft(4, '0');
    final m = date.month.toString().padLeft(2, '0');
    final d = date.day.toString().padLeft(2, '0');
    if (pattern == 'yyyy-MM-dd' || pattern == null) {
      return loc.startsWith('en') ? '$m/$d/$y' : '$y-$m-$d';
    }
    return '$y-$m-$d';
  }

  String formatNumber(num value, {int? fractionDigits}) {
    final s = fractionDigits == null
        ? value.toString()
        : value.toStringAsFixed(fractionDigits);
    if (_locale != enUS) return s;
    // light thousands separator for en
    final parts = s.split('.');
    final re = RegExp(r'\B(?=(\d{3})+(?!\d))');
    parts[0] = parts[0].replaceAllMapped(re, (m) => ',');
    return parts.join('.');
  }
}

/// Short aliases for widgets.
String bhT(String key, [Map<String, Object>? vars]) => BhL10n.instance.t(key, vars);

String bhTf(String key, String fallback, [Map<String, Object>? vars]) =>
    BhL10n.instance.tf(key, fallback, vars);
