// Auto-generated by scripts/flutter-sync-pubspec-from-manifest.py — do not edit.
import 'package:blockhub_flutter_core/blockhub_flutter_core.dart';
import 'package:flutter/material.dart';
import 'package:capability_shanghai_voice/capability_shanghai_voice.dart' deferred as def_voice;
import 'package:capability_dashboard/capability_dashboard.dart' deferred as def_dashboard;

const deferredCapabilityKeys = {
  'announce_board',
  'chart_bar',
  'chart_dashboard',
  'chart_funnel',
  'chart_line',
  'chat_voice',
  'data_export',
  'flutter_speech',
  'notify_email',
  'notify_inapp',
  'report_scheduled',
  'shanghai_voice',
  'shanghai_voice_stream',
};

bool isDeferredCapabilityKey(String key) => deferredCapabilityKeys.contains(key);

Future<Widget?> buildDeferredCapabilityPage({
  required String key,
  required AppBranding branding,
}) async {
  switch (key) {
    case 'shanghai_voice':
    case 'shanghai_voice_stream':
    case 'flutter_speech':
    case 'chat_voice':
      await def_voice.loadLibrary();
      return def_voice.ShanghaiVoicePage(branding: branding);
    case 'chart_dashboard':
    case 'chart_funnel':
    case 'chart_line':
    case 'chart_bar':
    case 'notify_inapp':
    case 'notify_email':
    case 'report_scheduled':
    case 'data_export':
    case 'announce_board':
      await def_dashboard.loadLibrary();
      return def_dashboard.DashboardPage(branding: branding);
    default:
      return null;
  }
}
