// Auto-generated by scripts/flutter-sync-pubspec-from-manifest.py — do not edit.
import 'package:blockhub_flutter_core/blockhub_flutter_core.dart';
import 'package:capability_approval_flow/capability_approval_flow.dart';
import 'package:capability_integration/capability_integration.dart';
import 'package:capability_audit_log/capability_audit_log.dart';
import 'package:capability_campaign_ops/capability_campaign_ops.dart';
import 'package:capability_dashboard/capability_dashboard.dart';
import 'package:capability_chat_qa/capability_chat_qa.dart';
import 'package:capability_class_schedule/capability_class_schedule.dart';
import 'package:capability_data_nl_query/capability_data_nl_query.dart';
import 'package:capability_deal_evidence/capability_deal_evidence.dart';
import 'package:capability_deco_material/capability_deco_material.dart';
import 'package:capability_delivery_order/capability_delivery_order.dart';
import 'package:capability_device_repair/capability_device_repair.dart';
import 'package:capability_expense_claim/capability_expense_claim.dart';
import 'package:capability_fitness_checkin/capability_fitness_checkin.dart';
import 'package:capability_game_support/capability_game_support.dart';
import 'package:capability_gov_service/capability_gov_service.dart';
import 'package:capability_hire_onboard/capability_hire_onboard.dart';
import 'package:capability_homework_qa/capability_homework_qa.dart';
import 'package:capability_hotel_booking/capability_hotel_booking.dart';
import 'package:capability_house_viewing/capability_house_viewing.dart';
import 'package:capability_inventory_count/capability_inventory_count.dart';
import 'package:capability_kb/capability_kb.dart';
import 'package:capability_kill_pipeline/capability_kill_pipeline.dart';
import 'package:capability_leave_request/capability_leave_request.dart';
import 'package:capability_legal_case/capability_legal_case.dart';
import 'package:capability_med_triage/capability_med_triage.dart';
import 'package:capability_member_loyalty/capability_member_loyalty.dart';
import 'package:capability_multi_agent/capability_multi_agent.dart';
import 'package:capability_nurse_shift/capability_nurse_shift.dart';
import 'package:capability_ops_kpi/capability_ops_kpi.dart';
import 'package:capability_pet_clinic/capability_pet_clinic.dart';
import 'package:capability_policy_qa/capability_policy_qa.dart';
import 'package:capability_property_repair/capability_property_repair.dart';
import 'package:capability_quality_inspect/capability_quality_inspect.dart';
import 'package:capability_quote_contract/capability_quote_contract.dart';
import 'package:capability_sales_lead/capability_sales_lead.dart';
import 'package:capability_school_notice/capability_school_notice.dart';
import 'package:capability_security_mask/capability_security_mask.dart';
import 'package:capability_shanghai_voice/capability_shanghai_voice.dart';
import 'package:capability_site_patrol/capability_site_patrol.dart';
import 'package:capability_study_coach/capability_study_coach.dart';
import 'package:capability_travel_plan/capability_travel_plan.dart';
import 'package:capability_wedding_plan/capability_wedding_plan.dart';

final _mod_approval_flow = const ApprovalFlowModule();
final _mod_audit_log = const AuditLogModule();
final _mod_campaign_ops = const CampaignOpsModule();
final _mod_dashboard = const DashboardModule();
final _mod_chat_qa = const ChatQaModule();
final _mod_class_schedule = const ClassScheduleModule();
final _mod_data_nl_query = const DataNlQueryModule();
final _mod_deal_evidence = const DealEvidenceModule();
final _mod_deco_material = const DecoMaterialModule();
final _mod_delivery_order = const DeliveryOrderModule();
final _mod_device_repair = const DeviceRepairModule();
final _mod_expense_claim = const ExpenseClaimModule();
final _mod_fitness_checkin = const FitnessCheckinModule();
final _mod_game_support = const GameSupportModule();
final _mod_gov_service = const GovServiceModule();
final _mod_hire_onboard = const HireOnboardModule();
final _mod_homework_qa = const HomeworkQaModule();
final _mod_hotel_booking = const HotelBookingModule();
final _mod_house_viewing = const HouseViewingModule();
final _mod_inventory_count = const InventoryCountModule();
final _mod_kb = const KbModule();
final _mod_kill_pipeline = const KillPipelineModule();
final _mod_leave_request = const LeaveRequestModule();
final _mod_legal_case = const LegalCaseModule();
final _mod_med_triage = const MedTriageModule();
final _mod_member_loyalty = const MemberLoyaltyModule();
final _mod_multi_agent = const MultiAgentModule();
final _mod_nurse_shift = const NurseShiftModule();
final _mod_ops_kpi = const OpsKpiModule();
final _mod_pet_clinic = const PetClinicModule();
final _mod_policy_qa = const PolicyQaModule();
final _mod_property_repair = const PropertyRepairModule();
final _mod_quality_inspect = const QualityInspectModule();
final _mod_quote_contract = const QuoteContractModule();
final _mod_sales_lead = const SalesLeadModule();
final _mod_school_notice = const SchoolNoticeModule();
final _mod_security_mask = const SecurityMaskModule();
final _mod_shanghai_voice = const ShanghaiVoiceModule();
final _mod_site_patrol = const SitePatrolModule();
final _mod_study_coach = const StudyCoachModule();
final _mod_travel_plan = const TravelPlanModule();
final _mod_wedding_plan = const WeddingPlanModule();

List<CapabilityModule> get generatedMelosCapabilityModules => [
  _mod_approval_flow,
  _mod_audit_log,
  _mod_campaign_ops,
  _mod_dashboard,
  _mod_chat_qa,
  _mod_class_schedule,
  _mod_data_nl_query,
  _mod_deal_evidence,
  _mod_deco_material,
  _mod_delivery_order,
  _mod_device_repair,
  _mod_expense_claim,
  _mod_fitness_checkin,
  _mod_game_support,
  _mod_gov_service,
  _mod_hire_onboard,
  _mod_homework_qa,
  _mod_hotel_booking,
  _mod_house_viewing,
  _mod_inventory_count,
  _mod_kb,
  _mod_kill_pipeline,
  _mod_leave_request,
  _mod_legal_case,
  _mod_med_triage,
  _mod_member_loyalty,
  _mod_multi_agent,
  _mod_nurse_shift,
  _mod_ops_kpi,
  _mod_pet_clinic,
  _mod_policy_qa,
  _mod_property_repair,
  _mod_quality_inspect,
  _mod_quote_contract,
  _mod_sales_lead,
  _mod_school_notice,
  _mod_security_mask,
  _mod_shanghai_voice,
  _mod_site_patrol,
  _mod_study_coach,
  _mod_travel_plan,
  _mod_wedding_plan,
];

final Map<String, CapabilityModule> generatedMelosModuleByKey = {
    'erp_connector': IntegrationModule(capabilityKey: 'erp_connector'),
    'meeting_booking': IntegrationModule(capabilityKey: 'meeting_booking'),
    'it_helpdesk': IntegrationModule(capabilityKey: 'it_helpdesk'),
    'asset_manage': IntegrationModule(capabilityKey: 'asset_manage'),
    'notify_im': IntegrationModule(capabilityKey: 'notify_im'),
    'rbac_page': IntegrationModule(capabilityKey: 'rbac_page'),
    'approval': _mod_approval_flow,
    'approval_conditional': _mod_approval_flow,
    'approval_countersign': _mod_approval_flow,
    'approval_esign': _mod_approval_flow,
    'approval_flow': _mod_approval_flow,
    'approval_inbox': _mod_approval_flow,
    'approval_remind': _mod_approval_flow,
    'audit_log': _mod_audit_log,
    'campaign_ops': _mod_campaign_ops,
    'chart_dashboard': _mod_dashboard,
    'chart_funnel': _mod_dashboard,
    'chat': _mod_chat_qa,
    'chat_qa': _mod_chat_qa,
    'chat_summary': _mod_chat_qa,
    'chat_voice': _mod_chat_qa,
    'class_schedule': _mod_class_schedule,
    'contract_editor': _mod_approval_flow,
    'contract_esign': _mod_approval_flow,
    'data_nl_query': _mod_data_nl_query,
    'deal_evidence': _mod_deal_evidence,
    'deco_material': _mod_deco_material,
    'delivery_order': _mod_delivery_order,
    'device_repair': _mod_device_repair,
    'expense_claim': _mod_expense_claim,
    'fitness_checkin': _mod_fitness_checkin,
    'form_widget': _mod_approval_flow,
    'game_support': _mod_game_support,
    'gov_service': _mod_gov_service,
    'hire_onboard': _mod_hire_onboard,
    'homework_qa': _mod_homework_qa,
    'hotel_booking': _mod_hotel_booking,
    'house_viewing': _mod_house_viewing,
    'inventory_count': _mod_inventory_count,
    'kb_document': _mod_kb,
    'kb_search': _mod_kb,
    'kill_pipeline': _mod_kill_pipeline,
    'leave_request': _mod_leave_request,
    'legal_case': _mod_legal_case,
    'list_widget': _mod_approval_flow,
    'med_triage': _mod_med_triage,
    'member_loyalty': _mod_member_loyalty,
    'multi_agent': _mod_multi_agent,
    'notify_email': _mod_dashboard,
    'notify_inapp': _mod_dashboard,
    'nurse_shift': _mod_nurse_shift,
    'ops_kpi': _mod_ops_kpi,
    'pet_clinic': _mod_pet_clinic,
    'policy_qa': _mod_policy_qa,
    'property_repair': _mod_property_repair,
    'quality_inspect': _mod_quality_inspect,
    'quote_contract': _mod_quote_contract,
    'sales_lead': _mod_sales_lead,
    'school_notice': _mod_school_notice,
    'security_mask': _mod_security_mask,
    'shanghai_voice': _mod_shanghai_voice,
    'shanghai_voice_stream': _mod_shanghai_voice,
    'site_patrol': _mod_site_patrol,
    'study_coach': _mod_study_coach,
    'travel_plan': _mod_travel_plan,
    'wedding_plan': _mod_wedding_plan,
};
