// Auto-generated by scripts/flutter-sync-pubspec-from-manifest.py — do not edit.
import 'package:blockhub_flutter_core/blockhub_flutter_core.dart';
import 'package:capability_chat_qa/capability_chat_qa.dart';
import 'package:capability_shanghai_voice/capability_shanghai_voice.dart';
import 'package:capability_approval_flow/capability_approval_flow.dart';
import 'package:capability_device_repair/capability_device_repair.dart';
import 'package:capability_quality_inspect/capability_quality_inspect.dart';
import 'package:capability_inventory_count/capability_inventory_count.dart';
import 'package:capability_member_loyalty/capability_member_loyalty.dart';
import 'package:capability_med_triage/capability_med_triage.dart';
import 'package:capability_nurse_shift/capability_nurse_shift.dart';
import 'package:capability_game_support/capability_game_support.dart';
import 'package:capability_school_notice/capability_school_notice.dart';
import 'package:capability_homework_qa/capability_homework_qa.dart';
import 'package:capability_audit_log/capability_audit_log.dart';
import 'package:capability_kb/capability_kb.dart';
import 'package:capability_dashboard/capability_dashboard.dart';
import 'package:capability_data_nl_query/capability_data_nl_query.dart';
import 'package:capability_integration/capability_integration.dart';
import 'package:capability_multi_agent/capability_multi_agent.dart';
import 'package:capability_security_mask/capability_security_mask.dart';
import 'package:capability_flutter_tools/capability_flutter_tools.dart';

final _mod_chat_qa = const ChatQaModule();
final _mod_shanghai_voice = const ShanghaiVoiceModule();
final _mod_approval_flow = const ApprovalFlowModule();
final _mod_device_repair = const DeviceRepairModule();
final _mod_quality_inspect = const QualityInspectModule();
final _mod_inventory_count = const InventoryCountModule();
final _mod_member_loyalty = const MemberLoyaltyModule();
final _mod_med_triage = const MedTriageModule();
final _mod_nurse_shift = const NurseShiftModule();
final _mod_game_support = const GameSupportModule();
final _mod_school_notice = const SchoolNoticeModule();
final _mod_homework_qa = const HomeworkQaModule();
final _mod_audit_log = const AuditLogModule();
final _mod_kb = const KbModule();
final _mod_dashboard = const DashboardModule();
final _mod_data_nl_query = const DataNlQueryModule();
final _mod_multi_agent = const MultiAgentModule();
final _mod_security_mask = const SecurityMaskModule();

List<CapabilityModule> get generatedMelosCapabilityModules => [
  _mod_chat_qa,
  _mod_shanghai_voice,
  _mod_approval_flow,
  _mod_device_repair,
  _mod_quality_inspect,
  _mod_inventory_count,
  _mod_member_loyalty,
  _mod_med_triage,
  _mod_nurse_shift,
  _mod_game_support,
  _mod_school_notice,
  _mod_homework_qa,
  _mod_audit_log,
  _mod_kb,
  _mod_dashboard,
  _mod_data_nl_query,
  _mod_multi_agent,
  _mod_security_mask,
];

final Map<String, CapabilityModule> generatedMelosModuleByKey = {
    'erp_connector': IntegrationModule(capabilityKey: 'erp_connector'),
    'meeting_booking': IntegrationModule(capabilityKey: 'meeting_booking'),
    'it_helpdesk': IntegrationModule(capabilityKey: 'it_helpdesk'),
    'asset_manage': IntegrationModule(capabilityKey: 'asset_manage'),
    'notify_im': IntegrationModule(capabilityKey: 'notify_im'),
    'rbac_page': IntegrationModule(capabilityKey: 'rbac_page'),
    'flutter_biometric': const FlutterToolsModule(capabilityKey: 'flutter_biometric'),
    'flutter_camera': const FlutterToolsModule(capabilityKey: 'flutter_camera'),
    'flutter_chart': const FlutterToolsModule(capabilityKey: 'flutter_chart'),
    'flutter_file_picker': const FlutterToolsModule(capabilityKey: 'flutter_file_picker'),
    'flutter_geolocation': const FlutterToolsModule(capabilityKey: 'flutter_geolocation'),
    'flutter_map': const FlutterToolsModule(capabilityKey: 'flutter_map'),
    'flutter_offline': const FlutterToolsModule(capabilityKey: 'flutter_offline'),
    'flutter_pdf': const FlutterToolsModule(capabilityKey: 'flutter_pdf'),
    'flutter_push': const FlutterToolsModule(capabilityKey: 'flutter_push'),
    'flutter_scan_qr': const FlutterToolsModule(capabilityKey: 'flutter_scan_qr'),
    'flutter_signature': const FlutterToolsModule(capabilityKey: 'flutter_signature'),
    'flutter_webview': const FlutterToolsModule(capabilityKey: 'flutter_webview'),
    'schedule_alarm': const FlutterToolsModule(capabilityKey: 'schedule_alarm'),
    'approval': _mod_approval_flow,
    'approval_conditional': _mod_approval_flow,
    'approval_countersign': _mod_approval_flow,
    'approval_esign': _mod_approval_flow,
    'approval_flow': _mod_approval_flow,
    'approval_inbox': _mod_approval_flow,
    'approval_remind': _mod_approval_flow,
    'audit_log': _mod_audit_log,
    'chart_dashboard': _mod_dashboard,
    'chart_funnel': _mod_dashboard,
    'chat': _mod_chat_qa,
    'chat_qa': _mod_chat_qa,
    'chat_summary': _mod_chat_qa,
    'chat_voice': _mod_chat_qa,
    'contract_editor': _mod_approval_flow,
    'contract_esign': _mod_approval_flow,
    'data_nl_query': _mod_data_nl_query,
    'device_repair': _mod_device_repair,
    'form_widget': _mod_approval_flow,
    'game_support': _mod_game_support,
    'homework_qa': _mod_homework_qa,
    'inventory_count': _mod_inventory_count,
    'kb_document': _mod_kb,
    'kb_search': _mod_kb,
    'list_widget': _mod_approval_flow,
    'med_triage': _mod_med_triage,
    'member_loyalty': _mod_member_loyalty,
    'multi_agent': _mod_multi_agent,
    'notify_email': _mod_dashboard,
    'notify_inapp': _mod_dashboard,
    'nurse_shift': _mod_nurse_shift,
    'quality_inspect': _mod_quality_inspect,
    'school_notice': _mod_school_notice,
    'security_mask': _mod_security_mask,
    'shanghai_voice': _mod_shanghai_voice,
    'shanghai_voice_stream': _mod_shanghai_voice,
};
